#nullable enable
namespace PhantomSemanticStudio.WinForms;

partial class ChatCorpusForm
{
    private System.Windows.Forms.TableLayoutPanel layoutRoot = null!;
    private System.Windows.Forms.Panel contentRoot = null!;
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        lblPrivacy = new System.Windows.Forms.Label();
        txtArchive = new System.Windows.Forms.TextBox();
        btnBrowse = new System.Windows.Forms.Button();
        btnImport = new System.Windows.Forms.Button();
        btnCancel = new System.Windows.Forms.Button();
        cmbCorpus = new System.Windows.Forms.ComboBox();
        btnRefresh = new System.Windows.Forms.Button();
        txtSearch = new System.Windows.Forms.TextBox();
        cmbChannel = new System.Windows.Forms.ComboBox();
        cmbLanguage = new System.Windows.Forms.ComboBox();
        lblLength = new System.Windows.Forms.Label();
        nudMinLength = new System.Windows.Forms.NumericUpDown();
        nudMaxLength = new System.Windows.Forms.NumericUpDown();
        dateFrom = new System.Windows.Forms.DateTimePicker();
        dateTo = new System.Windows.Forms.DateTimePicker();
        cmbDuplicates = new System.Windows.Forms.ComboBox();
        cmbNoise = new System.Windows.Forms.ComboBox();
        btnSearch = new System.Windows.Forms.Button();
        btnPrevious = new System.Windows.Forms.Button();
        btnNext = new System.Windows.Forms.Button();
        lblStats = new System.Windows.Forms.Label();
        lblSelected = new System.Windows.Forms.Label();
        btnClearSelection = new System.Windows.Forms.Button();
        listRows = new System.Windows.Forms.ListView();
        columnDate = new System.Windows.Forms.ColumnHeader();
        columnChannel = new System.Windows.Forms.ColumnHeader();
        columnLanguage = new System.Windows.Forms.ColumnHeader();
        columnPreview = new System.Windows.Forms.ColumnHeader();
        txtSelected = new System.Windows.Forms.TextBox();
        txtDetails = new System.Windows.Forms.TextBox();
        lblStatus = new System.Windows.Forms.Label();
        chkTransferReviewed = new System.Windows.Forms.CheckBox();
        btnTransfer = new System.Windows.Forms.Button();
        ((System.ComponentModel.ISupportInitialize)nudMinLength).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudMaxLength).BeginInit();
        layoutRoot = new System.Windows.Forms.TableLayoutPanel();
        contentRoot = new System.Windows.Forms.Panel();
        layoutRoot.SuspendLayout();
        contentRoot.SuspendLayout();
        SuspendLayout();
        layoutRoot.Name = "layoutRoot";
        layoutRoot.Size = new System.Drawing.Size(1280, 834);
        layoutRoot.Dock = System.Windows.Forms.DockStyle.Fill;
        layoutRoot.AutoScroll = true;
        layoutRoot.ColumnCount = 1;
        layoutRoot.RowCount = 1;
        layoutRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
        layoutRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
        layoutRoot.Margin = new System.Windows.Forms.Padding(0);
        contentRoot.Name = "contentRoot";
        contentRoot.Size = new System.Drawing.Size(1280, 834);
        contentRoot.MinimumSize = new System.Drawing.Size(1280, 834);
        contentRoot.Dock = System.Windows.Forms.DockStyle.Fill;
        contentRoot.Margin = new System.Windows.Forms.Padding(0);
        contentRoot.Padding = new System.Windows.Forms.Padding(0);

        lblPrivacy.Name = "lblPrivacy";
        lblPrivacy.Location = new System.Drawing.Point(12, 12);
        lblPrivacy.Size = new System.Drawing.Size(1256, 42);
        lblPrivacy.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblPrivacy.Text = "Только личный локальный анализ. TELL / FRIENDTELL не сохраняются; имена заголовков удаляются.\r\nВ публичных сообщениях возможны личные данные; скрытие приблизительное. Модель, кандидаты и одобрения не вызываются.";
        txtArchive.Name = "txtArchive";
        txtArchive.Location = new System.Drawing.Point(12, 62);
        txtArchive.Size = new System.Drawing.Size(850, 28);
        txtArchive.ReadOnly = true;
        txtArchive.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtArchive.TabIndex = 0;
        btnBrowse.Name = "btnBrowse";
        btnBrowse.Location = new System.Drawing.Point(876, 60);
        btnBrowse.Size = new System.Drawing.Size(122, 32);
        btnBrowse.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnBrowse.Text = "Открыть ZIP…";
        btnBrowse.TabIndex = 1;
        btnBrowse.Click += Browse_Click;
        btnImport.Name = "btnImport";
        btnImport.Location = new System.Drawing.Point(1006, 60);
        btnImport.Size = new System.Drawing.Size(132, 32);
        btnImport.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnImport.Text = "Импортировать";
        btnImport.TabIndex = 2;
        btnImport.Click += Import_Click;
        btnCancel.Name = "btnCancel";
        btnCancel.Location = new System.Drawing.Point(1146, 60);
        btnCancel.Size = new System.Drawing.Size(122, 32);
        btnCancel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnCancel.Text = "Отменить";
        btnCancel.Enabled = false;
        btnCancel.TabIndex = 3;
        btnCancel.Click += Cancel_Click;
        cmbCorpus.Name = "cmbCorpus";
        cmbCorpus.Location = new System.Drawing.Point(12, 106);
        cmbCorpus.Size = new System.Drawing.Size(1126, 28);
        cmbCorpus.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        cmbCorpus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbCorpus.TabIndex = 4;
        cmbCorpus.SelectedIndexChanged += Corpus_Changed;
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Location = new System.Drawing.Point(1146, 104);
        btnRefresh.Size = new System.Drawing.Size(122, 32);
        btnRefresh.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnRefresh.Text = "Обновить";
        btnRefresh.TabIndex = 5;
        btnRefresh.Click += Refresh_Click;
        txtSearch.Name = "txtSearch";
        txtSearch.Location = new System.Drawing.Point(12, 151);
        txtSearch.Size = new System.Drawing.Size(360, 28);
        txtSearch.MaxLength = 4000;
        txtSearch.PlaceholderText = "Поиск по тексту";
        txtSearch.TabIndex = 6;
        cmbChannel.Name = "cmbChannel";
        cmbChannel.Location = new System.Drawing.Point(384, 151);
        cmbChannel.Size = new System.Drawing.Size(220, 28);
        cmbChannel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbChannel.Items.AddRange(new object[] { "Все каналы", "ALL", "SHOUT", "TRADE", "PARTY", "CLAN", "ALLIANCE", "HERO_VOICE", "HERO", "BATTLEFIELD", "COMMANDCHANNEL_ALL", "COMMANDCHANNEL_COMMANDER" });
        cmbChannel.SelectedIndex = 0;
        cmbChannel.TabIndex = 7;
        cmbLanguage.Name = "cmbLanguage";
        cmbLanguage.Location = new System.Drawing.Point(616, 151);
        cmbLanguage.Size = new System.Drawing.Size(290, 28);
        cmbLanguage.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbLanguage.Items.AddRange(new object[] { "Все языки / неопределённость", "CYRILLIC", "LATIN_TRANSLIT_CANDIDATE", "EN_OR_OTHER", "MIXED", "UNKNOWN" });
        cmbLanguage.SelectedIndex = 0;
        cmbLanguage.TabIndex = 8;
        lblLength.Name = "lblLength";
        lblLength.Location = new System.Drawing.Point(918, 154);
        lblLength.Size = new System.Drawing.Size(94, 24);
        lblLength.Text = "Длина от/до";
        nudMinLength.Name = "nudMinLength";
        nudMinLength.Location = new System.Drawing.Point(1018, 151);
        nudMinLength.Size = new System.Drawing.Size(68, 28);
        nudMinLength.Maximum = 4000;
        nudMinLength.TabIndex = 9;
        nudMaxLength.Name = "nudMaxLength";
        nudMaxLength.Location = new System.Drawing.Point(1098, 151);
        nudMaxLength.Size = new System.Drawing.Size(68, 28);
        nudMaxLength.Maximum = 4000;
        nudMaxLength.Value = 4000;
        nudMaxLength.TabIndex = 10;
        dateFrom.Name = "dateFrom";
        dateFrom.Location = new System.Drawing.Point(12, 195);
        dateFrom.Size = new System.Drawing.Size(160, 28);
        dateFrom.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
        dateFrom.CustomFormat = "yyyy-MM-dd";
        dateFrom.ShowCheckBox = true;
        dateFrom.Checked = false;
        dateFrom.TabIndex = 11;
        dateTo.Name = "dateTo";
        dateTo.Location = new System.Drawing.Point(184, 195);
        dateTo.Size = new System.Drawing.Size(160, 28);
        dateTo.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
        dateTo.CustomFormat = "yyyy-MM-dd";
        dateTo.ShowCheckBox = true;
        dateTo.Checked = false;
        dateTo.TabIndex = 12;
        cmbDuplicates.Name = "cmbDuplicates";
        cmbDuplicates.Location = new System.Drawing.Point(356, 195);
        cmbDuplicates.Size = new System.Drawing.Size(200, 28);
        cmbDuplicates.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbDuplicates.Items.AddRange(new object[] { "Без дублей", "Включая дубли", "Только дубли" });
        cmbDuplicates.SelectedIndex = 0;
        cmbDuplicates.TabIndex = 13;
        cmbNoise.Name = "cmbNoise";
        cmbNoise.Location = new System.Drawing.Point(568, 195);
        cmbNoise.Size = new System.Drawing.Size(200, 28);
        cmbNoise.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbNoise.Items.AddRange(new object[] { "Без мусора / длинных", "Включая мусор", "Только мусор" });
        cmbNoise.SelectedIndex = 0;
        cmbNoise.TabIndex = 14;
        btnSearch.Name = "btnSearch";
        btnSearch.Location = new System.Drawing.Point(780, 193);
        btnSearch.Size = new System.Drawing.Size(126, 32);
        btnSearch.Text = "Найти";
        btnSearch.TabIndex = 15;
        btnSearch.Click += Search_Click;
        btnPrevious.Name = "btnPrevious";
        btnPrevious.Location = new System.Drawing.Point(918, 193);
        btnPrevious.Size = new System.Drawing.Size(116, 32);
        btnPrevious.Text = "← Назад";
        btnPrevious.TabIndex = 16;
        btnPrevious.Click += Previous_Click;
        btnNext.Name = "btnNext";
        btnNext.Location = new System.Drawing.Point(1046, 193);
        btnNext.Size = new System.Drawing.Size(120, 32);
        btnNext.Text = "Далее →";
        btnNext.TabIndex = 17;
        btnNext.Click += Next_Click;
        lblStats.Name = "lblStats";
        lblStats.Location = new System.Drawing.Point(12, 238);
        lblStats.Size = new System.Drawing.Size(800, 43);
        lblStats.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblStats.Text = "Корпус ещё не импортирован.";
        lblSelected.Name = "lblSelected";
        lblSelected.Location = new System.Drawing.Point(830, 238);
        lblSelected.Size = new System.Drawing.Size(438, 24);
        lblSelected.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        lblSelected.Text = "Выбрано явно: 0/20 • SOURCE_MATERIAL_ONLY";
        btnClearSelection.Name = "btnClearSelection";
        btnClearSelection.Location = new System.Drawing.Point(830, 267);
        btnClearSelection.Size = new System.Drawing.Size(190, 30);
        btnClearSelection.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnClearSelection.Text = "Снять все отметки";
        btnClearSelection.TabIndex = 19;
        btnClearSelection.Click += ClearSelection_Click;
        listRows.Name = "listRows";
        listRows.Location = new System.Drawing.Point(12, 338);
        listRows.Size = new System.Drawing.Size(800, 318);
        listRows.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        listRows.View = System.Windows.Forms.View.Details;
        listRows.CheckBoxes = true;
        listRows.FullRowSelect = true;
        listRows.HideSelection = false;
        listRows.MultiSelect = false;
        listRows.TabIndex = 18;
        listRows.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { columnDate, columnChannel, columnLanguage, columnPreview });
        listRows.ItemCheck += Row_Checked;
        listRows.SelectedIndexChanged += Row_Selected;
        columnDate.Text = "Дата (без timezone)";
        columnDate.Width = 166;
        columnChannel.Text = "Канал";
        columnChannel.Width = 104;
        columnLanguage.Text = "Язык / triage";
        columnLanguage.Width = 180;
        columnPreview.Text = "Фрагмент (скрытие PII приблизительное)";
        columnPreview.Width = 420;
        txtSelected.Name = "txtSelected";
        txtSelected.Location = new System.Drawing.Point(830, 338);
        txtSelected.Size = new System.Drawing.Size(438, 318);
        txtSelected.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
        txtSelected.Multiline = true;
        txtSelected.ReadOnly = true;
        txtSelected.ScrollBars = System.Windows.Forms.ScrollBars.Both;
        txtSelected.MaxLength = 0;
        txtSelected.TabIndex = 20;
        txtDetails.Name = "txtDetails";
        txtDetails.Location = new System.Drawing.Point(12, 670);
        txtDetails.Size = new System.Drawing.Size(1256, 112);
        txtDetails.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtDetails.Multiline = true;
        txtDetails.ReadOnly = true;
        txtDetails.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtDetails.MaxLength = 0;
        txtDetails.TabIndex = 21;
        lblStatus.Name = "lblStatus";
        lblStatus.Location = new System.Drawing.Point(12, 792);
        lblStatus.Size = new System.Drawing.Size(1256, 30);
        lblStatus.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblStatus.Text = "SOURCE_MATERIAL_ONLY. Никакого автоматического обучения.";
        chkTransferReviewed.Name = "chkTransferReviewed";
        chkTransferReviewed.Location = new System.Drawing.Point(830, 265);
        chkTransferReviewed.Size = new System.Drawing.Size(438, 32);
        chkTransferReviewed.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        chkTransferReviewed.Text = "Проверил полный preview и PII; разрешаю перенос";
        chkTransferReviewed.Checked = false;
        chkTransferReviewed.TabIndex = 22;
        btnTransfer.Name = "btnTransfer";
        btnTransfer.Location = new System.Drawing.Point(1030, 235);
        btnTransfer.Size = new System.Drawing.Size(238, 28);
        btnTransfer.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnTransfer.Text = "Передать в лабораторию";
        btnTransfer.Enabled = false;
        btnTransfer.TabIndex = 23;
        btnTransfer.Click += Transfer_Click;
        lblSelected.Size = new System.Drawing.Size(190, 24);
        btnClearSelection.Location = new System.Drawing.Point(634, 294);
        btnClearSelection.Size = new System.Drawing.Size(178, 32);
        contentRoot.Controls.Add(lblPrivacy);
        contentRoot.Controls.Add(txtArchive);
        contentRoot.Controls.Add(btnBrowse);
        contentRoot.Controls.Add(btnImport);
        contentRoot.Controls.Add(btnCancel);
        contentRoot.Controls.Add(cmbCorpus);
        contentRoot.Controls.Add(btnRefresh);
        contentRoot.Controls.Add(txtSearch);
        contentRoot.Controls.Add(cmbChannel);
        contentRoot.Controls.Add(cmbLanguage);
        contentRoot.Controls.Add(lblLength);
        contentRoot.Controls.Add(nudMinLength);
        contentRoot.Controls.Add(nudMaxLength);
        contentRoot.Controls.Add(dateFrom);
        contentRoot.Controls.Add(dateTo);
        contentRoot.Controls.Add(cmbDuplicates);
        contentRoot.Controls.Add(cmbNoise);
        contentRoot.Controls.Add(btnSearch);
        contentRoot.Controls.Add(btnPrevious);
        contentRoot.Controls.Add(btnNext);
        contentRoot.Controls.Add(lblStats);
        contentRoot.Controls.Add(lblSelected);
        contentRoot.Controls.Add(btnClearSelection);
        contentRoot.Controls.Add(listRows);
        contentRoot.Controls.Add(txtSelected);
        contentRoot.Controls.Add(txtDetails);
        contentRoot.Controls.Add(lblStatus);
        contentRoot.Controls.Add(chkTransferReviewed);
        contentRoot.Controls.Add(btnTransfer);
        AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
        AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
        ClientSize = new System.Drawing.Size(1280, 834);
        MinimumSize = new System.Drawing.Size(760, 420);
        Name = "ChatCorpusForm";
        Text = "Корпус чатов — приватный локальный анализ";
        StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
        Shown += Corpus_Shown;
        FormClosing += Corpus_Closing;
        ((System.ComponentModel.ISupportInitialize)nudMinLength).EndInit();
        ((System.ComponentModel.ISupportInitialize)nudMaxLength).EndInit();
        AutoScroll = false;
        layoutRoot.Controls.Add(contentRoot, 0, 0);
        Controls.Add(layoutRoot);
        contentRoot.ResumeLayout(false);
        layoutRoot.ResumeLayout(false);
        layoutRoot.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
    private System.Windows.Forms.Label lblPrivacy = null!;
    private System.Windows.Forms.TextBox txtArchive = null!;
    private System.Windows.Forms.Button btnBrowse = null!;
    private System.Windows.Forms.Button btnImport = null!;
    private System.Windows.Forms.Button btnCancel = null!;
    private System.Windows.Forms.ComboBox cmbCorpus = null!;
    private System.Windows.Forms.Button btnRefresh = null!;
    private System.Windows.Forms.TextBox txtSearch = null!;
    private System.Windows.Forms.ComboBox cmbChannel = null!;
    private System.Windows.Forms.ComboBox cmbLanguage = null!;
    private System.Windows.Forms.Label lblLength = null!;
    private System.Windows.Forms.NumericUpDown nudMinLength = null!;
    private System.Windows.Forms.NumericUpDown nudMaxLength = null!;
    private System.Windows.Forms.DateTimePicker dateFrom = null!;
    private System.Windows.Forms.DateTimePicker dateTo = null!;
    private System.Windows.Forms.ComboBox cmbDuplicates = null!;
    private System.Windows.Forms.ComboBox cmbNoise = null!;
    private System.Windows.Forms.Button btnSearch = null!;
    private System.Windows.Forms.Button btnPrevious = null!;
    private System.Windows.Forms.Button btnNext = null!;
    private System.Windows.Forms.Label lblStats = null!;
    private System.Windows.Forms.Label lblSelected = null!;
    private System.Windows.Forms.Button btnClearSelection = null!;
    private System.Windows.Forms.ListView listRows = null!;
    private System.Windows.Forms.ColumnHeader columnDate = null!;
    private System.Windows.Forms.ColumnHeader columnChannel = null!;
    private System.Windows.Forms.ColumnHeader columnLanguage = null!;
    private System.Windows.Forms.ColumnHeader columnPreview = null!;
    private System.Windows.Forms.TextBox txtSelected = null!;
    private System.Windows.Forms.TextBox txtDetails = null!;
    private System.Windows.Forms.Label lblStatus = null!;
    private System.Windows.Forms.CheckBox chkTransferReviewed = null!;
    private System.Windows.Forms.Button btnTransfer = null!;
}
