#nullable enable
namespace PhantomSemanticStudio.WinForms;

partial class DialogueLabForm
{
    private System.ComponentModel.IContainer? components = null;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
        lblSource = new System.Windows.Forms.Label();
        cmbWorld = new System.Windows.Forms.ComboBox();
        cmbBand = new System.Windows.Forms.ComboBox();
        cmbRegister = new System.Windows.Forms.ComboBox();
        lblContext = new System.Windows.Forms.Label();
        btnClear = new System.Windows.Forms.Button();
        btnCancel = new System.Windows.Forms.Button();
        tabsLab = new System.Windows.Forms.TabControl();
        tabDialogue = new System.Windows.Forms.TabPage();
        tabMentor = new System.Windows.Forms.TabPage();
        tabCorpus = new System.Windows.Forms.TabPage();
        txtTranscript = new System.Windows.Forms.TextBox();
        listTurns = new System.Windows.Forms.ListBox();
        txtTrace = new System.Windows.Forms.TextBox();
        txtInput = new System.Windows.Forms.TextBox();
        btnSend = new System.Windows.Forms.Button();
        chkMentor = new System.Windows.Forms.CheckBox();
        lblMentor = new System.Windows.Forms.Label();
        lblCorpus = new System.Windows.Forms.Label();
        lblStatus = new System.Windows.Forms.Label();
        btnMentorPreview = new System.Windows.Forms.Button();
        txtMentorPreview = new System.Windows.Forms.TextBox();
        chkContextReviewed = new System.Windows.Forms.CheckBox();
        btnAskMentor = new System.Windows.Forms.Button();
        txtAdvice = new System.Windows.Forms.TextBox();
        cmbConfirmWorld = new System.Windows.Forms.ComboBox();
        txtClarification = new System.Windows.Forms.TextBox();
        btnConfirm = new System.Windows.Forms.Button();
        btnDiscardMentor = new System.Windows.Forms.Button();
        btnUseMentorNote = new System.Windows.Forms.Button();
        txtNote = new System.Windows.Forms.TextBox();
        cmbAct = new System.Windows.Forms.ComboBox();
        cmbTopic = new System.Windows.Forms.ComboBox();
        cmbGender = new System.Windows.Forms.ComboBox();
        chkScopeReviewed = new System.Windows.Forms.CheckBox();
        btnSaveLesson = new System.Windows.Forms.Button();
        btnAddNote = new System.Windows.Forms.Button();
        btnSaveHistory = new System.Windows.Forms.Button();
        btnChooseCorpus = new System.Windows.Forms.Button();
        listExcerpts = new System.Windows.Forms.ListView();
        columnExcerptId = new System.Windows.Forms.ColumnHeader();
        columnExcerptLanguage = new System.Windows.Forms.ColumnHeader();
        columnExcerptChannel = new System.Windows.Forms.ColumnHeader();
        txtExcerpt = new System.Windows.Forms.TextBox();
        lblExcerptEdit = new System.Windows.Forms.Label();
        cmbLanguageOverride = new System.Windows.Forms.ComboBox();
        txtShareText = new System.Windows.Forms.TextBox();
        cmbTransform = new System.Windows.Forms.ComboBox();
        txtModelPreview = new System.Windows.Forms.TextBox();
        chkPiiReviewed = new System.Windows.Forms.CheckBox();
        chkShareCorpus = new System.Windows.Forms.CheckBox();
        btnTranslate = new System.Windows.Forms.Button();
        listSuggestions = new System.Windows.Forms.ListBox();
        txtCorpusAdvice = new System.Windows.Forms.TextBox();
        btnUseSuggestion = new System.Windows.Forms.Button();
        tabsLab.SuspendLayout();
        tabDialogue.SuspendLayout();
        tabMentor.SuspendLayout();
        tabCorpus.SuspendLayout();
        SuspendLayout();
        lblSource.Name = "lblSource";
        lblSource.Location = new System.Drawing.Point(12, 8);
        lblSource.Size = new System.Drawing.Size(1256, 44);
        lblSource.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblSource.Text = "Нет импортированного Semantic Pack. PACK_CATALOG_APPROXIMATE / NOT_JAVA_RUNTIME_PARITY";
        cmbWorld.Name = "cmbWorld";
        cmbWorld.Location = new System.Drawing.Point(12, 60);
        cmbWorld.Size = new System.Drawing.Size(140, 28);
        cmbWorld.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbWorld.Items.AddRange(new object[] { "AUTO", "GAME", "REAL", "MIXED" });
        cmbWorld.SelectedIndex = 0;
        cmbWorld.TabIndex = 0;
        cmbWorld.SelectedIndexChanged += Context_Changed;
        cmbBand.Name = "cmbBand";
        cmbBand.Location = new System.Drawing.Point(164, 60);
        cmbBand.Size = new System.Drawing.Size(150, 28);
        cmbBand.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbBand.Items.AddRange(new object[] { "UNKNOWN", "NEUTRAL", "FAMILIAR", "TRUSTED", "RIVAL", "TENSE", "HOSTILE" });
        cmbBand.SelectedIndex = 0;
        cmbBand.TabIndex = 1;
        cmbBand.SelectedIndexChanged += Context_Changed;
        cmbRegister.Name = "cmbRegister";
        cmbRegister.Location = new System.Drawing.Point(326, 60);
        cmbRegister.Size = new System.Drawing.Size(140, 28);
        cmbRegister.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbRegister.Items.AddRange(new object[] { "NEUTRAL", "CASUAL" });
        cmbRegister.SelectedIndex = 0;
        cmbRegister.TabIndex = 2;
        cmbRegister.SelectedIndexChanged += Context_Changed;
        lblContext.Name = "lblContext";
        lblContext.Location = new System.Drawing.Point(478, 60);
        lblContext.Size = new System.Drawing.Size(430, 36);
        lblContext.Text = "Контекст / отношения / стиль\r\nWORLD_ADVISORY_ONLY — гипотеза редактора";
        btnClear.Name = "btnClear";
        btnClear.Location = new System.Drawing.Point(920, 58);
        btnClear.Size = new System.Drawing.Size(168, 34);
        btnClear.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnClear.Text = "Очистить историю";
        btnClear.TabIndex = 3;
        btnClear.Click += Clear_Click;
        btnCancel.Name = "btnCancel";
        btnCancel.Location = new System.Drawing.Point(1100, 58);
        btnCancel.Size = new System.Drawing.Size(168, 34);
        btnCancel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnCancel.Text = "Отменить операцию";
        btnCancel.Enabled = false;
        btnCancel.TabIndex = 4;
        btnCancel.Click += Cancel_Click;
        tabsLab.Name = "tabsLab";
        tabsLab.Location = new System.Drawing.Point(12, 104);
        tabsLab.Size = new System.Drawing.Size(1256, 690);
        tabsLab.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        tabsLab.Controls.Add(tabDialogue);
        tabsLab.Controls.Add(tabMentor);
        tabsLab.Controls.Add(tabCorpus);
        tabsLab.TabIndex = 5;
        tabDialogue.Name = "tabDialogue";
        tabDialogue.Size = new System.Drawing.Size(1248, 654);
        tabDialogue.Text = "Диалог с каталогом";
        tabDialogue.UseVisualStyleBackColor = true;
        tabMentor.Name = "tabMentor";
        tabMentor.Size = new System.Drawing.Size(1248, 654);
        tabMentor.Text = "Наставник и заметки";
        tabMentor.UseVisualStyleBackColor = true;
        tabCorpus.Name = "tabCorpus";
        tabCorpus.Size = new System.Drawing.Size(1248, 654);
        tabCorpus.Text = "Выбранные public фрагменты";
        tabCorpus.UseVisualStyleBackColor = true;
        txtTranscript.Name = "txtTranscript";
        txtTranscript.Location = new System.Drawing.Point(10, 12);
        txtTranscript.Size = new System.Drawing.Size(774, 510);
        txtTranscript.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtTranscript.Multiline = true;
        txtTranscript.ReadOnly = true;
        txtTranscript.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtTranscript.MaxLength = 0;
        txtTranscript.TabIndex = 0;
        listTurns.Name = "listTurns";
        listTurns.Location = new System.Drawing.Point(800, 12);
        listTurns.Size = new System.Drawing.Size(430, 130);
        listTurns.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        listTurns.TabIndex = 1;
        listTurns.SelectedIndexChanged += Turn_Selected;
        txtTrace.Name = "txtTrace";
        txtTrace.Location = new System.Drawing.Point(800, 154);
        txtTrace.Size = new System.Drawing.Size(430, 368);
        txtTrace.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
        txtTrace.Multiline = true;
        txtTrace.ReadOnly = true;
        txtTrace.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtTrace.MaxLength = 0;
        txtTrace.TabIndex = 2;
        txtInput.Name = "txtInput";
        txtInput.Location = new System.Drawing.Point(10, 540);
        txtInput.Size = new System.Drawing.Size(1004, 90);
        txtInput.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtInput.Multiline = true;
        txtInput.MaxLength = 1024;
        txtInput.PlaceholderText = "Ваша реплика (matching до 256 символов; длиннее — честный отказ без обрезки)";
        txtInput.TabIndex = 3;
        txtInput.TextChanged += Input_Changed;
        btnSend.Name = "btnSend";
        btnSend.Location = new System.Drawing.Point(1030, 540);
        btnSend.Size = new System.Drawing.Size(200, 90);
        btnSend.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
        btnSend.Text = "Ответ каталога\r\nбез Gemma";
        btnSend.Enabled = false;
        btnSend.TabIndex = 4;
        btnSend.Click += Send_Click;
        chkMentor.Name = "chkMentor";
        chkMentor.Location = new System.Drawing.Point(12, 12);
        chkMentor.Size = new System.Drawing.Size(550, 30);
        chkMentor.Text = "Gemma помогает — ограниченный контекст локальному LM Studio";
        chkMentor.Checked = false;
        chkMentor.Enabled = false;
        chkMentor.TabIndex = 0;
        chkMentor.CheckedChanged += Mentor_Changed;
        lblMentor.Name = "lblMentor";
        lblMentor.Location = new System.Drawing.Point(12, 50);
        lblMentor.Size = new System.Drawing.Size(1000, 44);
        lblMentor.Text = "Наставник — отдельная роль MENTOR; ответы ПАКА никогда не генерируются моделью.\r\nЭфемерная история, никакого автоматического обучения или одобрения.";
        btnMentorPreview.Name = "btnMentorPreview";
        btnMentorPreview.Location = new System.Drawing.Point(650, 10);
        btnMentorPreview.Size = new System.Drawing.Size(240, 32);
        btnMentorPreview.Text = "Подготовить context preview";
        btnMentorPreview.Enabled = false;
        btnMentorPreview.TabIndex = 1;
        btnMentorPreview.Click += MentorPreview_Click;
        txtMentorPreview.Name = "txtMentorPreview";
        txtMentorPreview.Location = new System.Drawing.Point(12, 96);
        txtMentorPreview.Size = new System.Drawing.Size(1218, 108);
        txtMentorPreview.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtMentorPreview.Multiline = true;
        txtMentorPreview.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtMentorPreview.MaxLength = 8192;
        txtMentorPreview.TabIndex = 2;
        txtMentorPreview.TextChanged += MentorPreview_Changed;
        chkContextReviewed.Name = "chkContextReviewed";
        chkContextReviewed.Location = new System.Drawing.Point(12, 210);
        chkContextReviewed.Size = new System.Drawing.Size(850, 30);
        chkContextReviewed.Text = "Проверил и замаскировал точный context preview; разрешаю один локальный запрос";
        chkContextReviewed.Checked = false;
        chkContextReviewed.TabIndex = 3;
        chkContextReviewed.CheckedChanged += ReviewPermission_Changed;
        btnAskMentor.Name = "btnAskMentor";
        btnAskMentor.Location = new System.Drawing.Point(1010, 208);
        btnAskMentor.Size = new System.Drawing.Size(220, 34);
        btnAskMentor.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnAskMentor.Text = "Спросить Gemma (1 POST)";
        btnAskMentor.Enabled = false;
        btnAskMentor.TabIndex = 4;
        btnAskMentor.Click += AskMentor_Click;
        txtAdvice.Name = "txtAdvice";
        txtAdvice.Location = new System.Drawing.Point(12, 250);
        txtAdvice.Size = new System.Drawing.Size(738, 140);
        txtAdvice.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtAdvice.Multiline = true;
        txtAdvice.ReadOnly = true;
        txtAdvice.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtAdvice.MaxLength = 0;
        txtAdvice.TabIndex = 5;
        cmbConfirmWorld.Name = "cmbConfirmWorld";
        cmbConfirmWorld.Location = new System.Drawing.Point(770, 250);
        cmbConfirmWorld.Size = new System.Drawing.Size(220, 28);
        cmbConfirmWorld.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        cmbConfirmWorld.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbConfirmWorld.Items.AddRange(new object[] { "UNKNOWN", "GAME", "REAL", "MIXED" });
        cmbConfirmWorld.SelectedIndex = 0;
        cmbConfirmWorld.TabIndex = 6;
        txtClarification.Name = "txtClarification";
        txtClarification.Location = new System.Drawing.Point(770, 286);
        txtClarification.Size = new System.Drawing.Size(460, 28);
        txtClarification.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        txtClarification.MaxLength = 400;
        txtClarification.PlaceholderText = "Мой ответ на вопрос наставника";
        txtClarification.TabIndex = 7;
        btnConfirm.Name = "btnConfirm";
        btnConfirm.Location = new System.Drawing.Point(770, 322);
        btnConfirm.Size = new System.Drawing.Size(220, 32);
        btnConfirm.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnConfirm.Text = "Подтвердить контекст";
        btnConfirm.Enabled = false;
        btnConfirm.TabIndex = 8;
        btnConfirm.Click += Confirm_Click;
        btnDiscardMentor.Name = "btnDiscardMentor";
        btnDiscardMentor.Location = new System.Drawing.Point(1002, 322);
        btnDiscardMentor.Size = new System.Drawing.Size(228, 32);
        btnDiscardMentor.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnDiscardMentor.Text = "Отбросить совет";
        btnDiscardMentor.TabIndex = 9;
        btnDiscardMentor.Click += DiscardMentor_Click;
        btnUseMentorNote.Name = "btnUseMentorNote";
        btnUseMentorNote.Location = new System.Drawing.Point(770, 362);
        btnUseMentorNote.Size = new System.Drawing.Size(460, 30);
        btnUseMentorNote.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
        btnUseMentorNote.Text = "Предложение наставника → редактируемая заметка";
        btnUseMentorNote.Enabled = false;
        btnUseMentorNote.TabIndex = 10;
        btnUseMentorNote.Click += UseMentorNote_Click;
        txtNote.Name = "txtNote";
        txtNote.Location = new System.Drawing.Point(12, 404);
        txtNote.Size = new System.Drawing.Size(1218, 72);
        txtNote.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtNote.Multiline = true;
        txtNote.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtNote.MaxLength = 4000;
        txtNote.PlaceholderText = "Редакционная заметка: эфемерна до отдельного сохранения с scope";
        txtNote.TabIndex = 11;
        txtNote.TextChanged += Note_Changed;
        cmbAct.Name = "cmbAct";
        cmbAct.Location = new System.Drawing.Point(12, 490);
        cmbAct.Size = new System.Drawing.Size(370, 28);
        cmbAct.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        cmbAct.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbAct.TabIndex = 12;
        cmbAct.SelectedIndexChanged += Act_Changed;
        cmbTopic.Name = "cmbTopic";
        cmbTopic.Location = new System.Drawing.Point(394, 490);
        cmbTopic.Size = new System.Drawing.Size(370, 28);
        cmbTopic.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        cmbTopic.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbTopic.TabIndex = 13;
        cmbTopic.SelectedIndexChanged += Scope_Changed;
        cmbGender.Name = "cmbGender";
        cmbGender.Location = new System.Drawing.Point(776, 490);
        cmbGender.Size = new System.Drawing.Size(150, 28);
        cmbGender.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        cmbGender.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbGender.Items.AddRange(new object[] { "ANY", "FEMALE", "MALE" });
        cmbGender.SelectedIndex = 0;
        cmbGender.TabIndex = 14;
        cmbGender.SelectedIndexChanged += Scope_Changed;
        chkScopeReviewed.Name = "chkScopeReviewed";
        chkScopeReviewed.Location = new System.Drawing.Point(12, 526);
        chkScopeReviewed.Size = new System.Drawing.Size(1218, 32);
        chkScopeReviewed.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        chkScopeReviewed.Text = "Проверил текст, source и Act / Topic / Gender ниже; Band / Register сверху. Только scoped lesson, без approval/XML";
        chkScopeReviewed.Checked = false;
        chkScopeReviewed.TabIndex = 15;
        btnAddNote.Name = "btnAddNote";
        btnAddNote.Location = new System.Drawing.Point(12, 574);
        btnAddNote.Size = new System.Drawing.Size(288, 40);
        btnAddNote.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        btnAddNote.Text = "Добавить EDITOR_NOTE локально";
        btnAddNote.TabIndex = 16;
        btnAddNote.Click += AddNote_Click;
        btnSaveLesson.Name = "btnSaveLesson";
        btnSaveLesson.Location = new System.Drawing.Point(314, 574);
        btnSaveLesson.Size = new System.Drawing.Size(290, 40);
        btnSaveLesson.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        btnSaveLesson.Text = "Сохранить scoped lesson";
        btnSaveLesson.Enabled = false;
        btnSaveLesson.TabIndex = 17;
        btnSaveLesson.Click += SaveLesson_Click;
        btnSaveHistory.Name = "btnSaveHistory";
        btnSaveHistory.Location = new System.Drawing.Point(650, 574);
        btnSaveHistory.Size = new System.Drawing.Size(420, 40);
        btnSaveHistory.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        btnSaveHistory.Text = "Явно сохранить private историю в workspace/labs";
        btnSaveHistory.Enabled = false;
        btnSaveHistory.TabIndex = 18;
        btnSaveHistory.Click += SaveHistory_Click;
        lblCorpus.Name = "lblCorpus";
        lblCorpus.Location = new System.Drawing.Point(284, 12);
        lblCorpus.Size = new System.Drawing.Size(946, 44);
        lblCorpus.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblCorpus.Text = "SOURCE_MATERIAL_ONLY. До 20 public previews; имена/PII могут остаться: маскирование приблизительное.\r\nОтметьте только 1–3 для отдельного запроса. Gemma получает только точный проверенный preview ниже.";
        btnChooseCorpus.Name = "btnChooseCorpus";
        btnChooseCorpus.Location = new System.Drawing.Point(12, 10);
        btnChooseCorpus.Size = new System.Drawing.Size(260, 36);
        btnChooseCorpus.Text = "Выбрать public фрагменты…";
        btnChooseCorpus.Enabled = false;
        btnChooseCorpus.TabIndex = 0;
        btnChooseCorpus.Click += ChooseCorpus_Click;
        listExcerpts.Name = "listExcerpts";
        listExcerpts.Location = new System.Drawing.Point(12, 62);
        listExcerpts.Size = new System.Drawing.Size(440, 150);
        listExcerpts.View = System.Windows.Forms.View.Details;
        listExcerpts.CheckBoxes = true;
        listExcerpts.FullRowSelect = true;
        listExcerpts.HideSelection = false;
        listExcerpts.MultiSelect = false;
        listExcerpts.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { columnExcerptId, columnExcerptLanguage, columnExcerptChannel });
        listExcerpts.TabIndex = 1;
        listExcerpts.ItemCheck += Excerpt_Checked;
        listExcerpts.SelectedIndexChanged += Excerpt_Selected;
        columnExcerptId.Text = "Ref";
        columnExcerptId.Width = 95;
        columnExcerptLanguage.Text = "Языковая гипотеза";
        columnExcerptLanguage.Width = 230;
        columnExcerptChannel.Text = "Канал";
        columnExcerptChannel.Width = 100;
        txtExcerpt.Name = "txtExcerpt";
        txtExcerpt.Location = new System.Drawing.Point(470, 62);
        txtExcerpt.Size = new System.Drawing.Size(760, 150);
        txtExcerpt.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtExcerpt.Multiline = true;
        txtExcerpt.ReadOnly = true;
        txtExcerpt.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtExcerpt.MaxLength = 0;
        txtExcerpt.TabIndex = 2;
        lblExcerptEdit.Name = "lblExcerptEdit";
        lblExcerptEdit.Location = new System.Drawing.Point(12, 222);
        lblExcerptEdit.Size = new System.Drawing.Size(1218, 24);
        lblExcerptEdit.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblExcerptEdit.Text = "Выберите строку слева; правьте только её текст справа. Латиница ≠ транслит. Для LM сократите вручную до 1024 символов.";
        cmbLanguageOverride.Name = "cmbLanguageOverride";
        cmbLanguageOverride.Location = new System.Drawing.Point(12, 250);
        cmbLanguageOverride.Size = new System.Drawing.Size(440, 28);
        cmbLanguageOverride.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbLanguageOverride.Items.AddRange(new object[] { "UNKNOWN — непонятно", "RU_TRANSLIT — возможный транслит", "OTHER_LANGUAGE — иностранный" });
        cmbLanguageOverride.SelectedIndex = 0;
        cmbLanguageOverride.TabIndex = 3;
        cmbLanguageOverride.SelectedIndexChanged += CorpusText_Changed;
        txtShareText.Name = "txtShareText";
        txtShareText.Location = new System.Drawing.Point(470, 250);
        txtShareText.Size = new System.Drawing.Size(760, 100);
        txtShareText.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtShareText.Multiline = true;
        txtShareText.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtShareText.MaxLength = 4000;
        txtShareText.TabIndex = 4;
        txtShareText.TextChanged += CorpusText_Changed;
        cmbTransform.Name = "cmbTransform";
        cmbTransform.Location = new System.Drawing.Point(12, 304);
        cmbTransform.Size = new System.Drawing.Size(440, 28);
        cmbTransform.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        cmbTransform.Items.AddRange(new object[] { "RESTORE_RU_TRANSLIT", "TRANSLATE_TO_RUSSIAN", "LEAVE_AS_IS" });
        cmbTransform.SelectedIndex = 0;
        cmbTransform.TabIndex = 5;
        cmbTransform.SelectedIndexChanged += Transform_Changed;
        txtModelPreview.Name = "txtModelPreview";
        txtModelPreview.Location = new System.Drawing.Point(12, 360);
        txtModelPreview.Size = new System.Drawing.Size(1218, 100);
        txtModelPreview.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtModelPreview.Multiline = true;
        txtModelPreview.ReadOnly = true;
        txtModelPreview.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtModelPreview.MaxLength = 0;
        txtModelPreview.TabIndex = 6;
        chkPiiReviewed.Name = "chkPiiReviewed";
        chkPiiReviewed.Location = new System.Drawing.Point(12, 470);
        chkPiiReviewed.Size = new System.Drawing.Size(950, 28);
        chkPiiReviewed.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        chkPiiReviewed.Text = "Проверил ВСЕ отмеченные тексты preview; вручную удалил имена и личные данные (скрытие best-effort)";
        chkPiiReviewed.Checked = false;
        chkPiiReviewed.TabIndex = 7;
        chkPiiReviewed.CheckedChanged += ReviewPermission_Changed;
        chkShareCorpus.Name = "chkShareCorpus";
        chkShareCorpus.Location = new System.Drawing.Point(12, 503);
        chkShareCorpus.Size = new System.Drawing.Size(950, 28);
        chkShareCorpus.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        chkShareCorpus.Text = "Отдельно разрешаю этим 1–3 sanitized текстам один локальный Gemma POST; без применения к паку";
        chkShareCorpus.Checked = false;
        chkShareCorpus.TabIndex = 8;
        chkShareCorpus.CheckedChanged += ReviewPermission_Changed;
        btnTranslate.Name = "btnTranslate";
        btnTranslate.Location = new System.Drawing.Point(980, 498);
        btnTranslate.Size = new System.Drawing.Size(250, 38);
        btnTranslate.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
        btnTranslate.Text = "Предложить перевод / транслит";
        btnTranslate.Enabled = false;
        btnTranslate.TabIndex = 9;
        btnTranslate.Click += Translate_Click;
        listSuggestions.Name = "listSuggestions";
        listSuggestions.Location = new System.Drawing.Point(12, 548);
        listSuggestions.Size = new System.Drawing.Size(200, 80);
        listSuggestions.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
        listSuggestions.TabIndex = 10;
        listSuggestions.SelectedIndexChanged += Suggestion_Selected;
        txtCorpusAdvice.Name = "txtCorpusAdvice";
        txtCorpusAdvice.Location = new System.Drawing.Point(224, 548);
        txtCorpusAdvice.Size = new System.Drawing.Size(740, 80);
        txtCorpusAdvice.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        txtCorpusAdvice.Multiline = true;
        txtCorpusAdvice.ReadOnly = true;
        txtCorpusAdvice.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
        txtCorpusAdvice.MaxLength = 0;
        txtCorpusAdvice.TabIndex = 11;
        btnUseSuggestion.Name = "btnUseSuggestion";
        btnUseSuggestion.Location = new System.Drawing.Point(980, 590);
        btnUseSuggestion.Size = new System.Drawing.Size(250, 36);
        btnUseSuggestion.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
        btnUseSuggestion.Text = "Выбранное → EDITOR_NOTE";
        btnUseSuggestion.Enabled = false;
        btnUseSuggestion.TabIndex = 12;
        btnUseSuggestion.Click += UseSuggestion_Click;
        lblStatus.Name = "lblStatus";
        lblStatus.Location = new System.Drawing.Point(12, 802);
        lblStatus.Size = new System.Drawing.Size(1256, 30);
        lblStatus.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
        lblStatus.Text = "Ожидание. LM opt-in OFF; Java NOT_RUN. История локальна и эфемерна.";
        tabDialogue.Controls.Add(txtTranscript);
        tabDialogue.Controls.Add(listTurns);
        tabDialogue.Controls.Add(txtTrace);
        tabDialogue.Controls.Add(txtInput);
        tabDialogue.Controls.Add(btnSend);
        tabMentor.Controls.Add(chkMentor);
        tabMentor.Controls.Add(lblMentor);
        tabMentor.Controls.Add(btnMentorPreview);
        tabMentor.Controls.Add(txtMentorPreview);
        tabMentor.Controls.Add(chkContextReviewed);
        tabMentor.Controls.Add(btnAskMentor);
        tabMentor.Controls.Add(txtAdvice);
        tabMentor.Controls.Add(cmbConfirmWorld);
        tabMentor.Controls.Add(txtClarification);
        tabMentor.Controls.Add(btnConfirm);
        tabMentor.Controls.Add(btnDiscardMentor);
        tabMentor.Controls.Add(btnUseMentorNote);
        tabMentor.Controls.Add(txtNote);
        tabMentor.Controls.Add(cmbAct);
        tabMentor.Controls.Add(cmbTopic);
        tabMentor.Controls.Add(cmbGender);
        tabMentor.Controls.Add(chkScopeReviewed);
        tabMentor.Controls.Add(btnAddNote);
        tabMentor.Controls.Add(btnSaveLesson);
        tabMentor.Controls.Add(btnSaveHistory);
        tabCorpus.Controls.Add(lblCorpus);
        tabCorpus.Controls.Add(btnChooseCorpus);
        tabCorpus.Controls.Add(listExcerpts);
        tabCorpus.Controls.Add(txtExcerpt);
        tabCorpus.Controls.Add(lblExcerptEdit);
        tabCorpus.Controls.Add(cmbLanguageOverride);
        tabCorpus.Controls.Add(txtShareText);
        tabCorpus.Controls.Add(cmbTransform);
        tabCorpus.Controls.Add(txtModelPreview);
        tabCorpus.Controls.Add(chkPiiReviewed);
        tabCorpus.Controls.Add(chkShareCorpus);
        tabCorpus.Controls.Add(btnTranslate);
        tabCorpus.Controls.Add(listSuggestions);
        tabCorpus.Controls.Add(txtCorpusAdvice);
        tabCorpus.Controls.Add(btnUseSuggestion);
        Controls.Add(lblSource);
        Controls.Add(cmbWorld);
        Controls.Add(cmbBand);
        Controls.Add(cmbRegister);
        Controls.Add(lblContext);
        Controls.Add(btnClear);
        Controls.Add(btnCancel);
        Controls.Add(tabsLab);
        Controls.Add(lblStatus);
        AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
        AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
        ClientSize = new System.Drawing.Size(1280, 840);
        MinimumSize = new System.Drawing.Size(1200, 800);
        Name = "DialogueLabForm";
        Text = "Лаборатория диалогов — каталог и отдельный наставник";
        StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
        FormClosing += Lab_Closing;
        tabsLab.ResumeLayout(false);
        tabDialogue.ResumeLayout(false);
        tabDialogue.PerformLayout();
        tabMentor.ResumeLayout(false);
        tabMentor.PerformLayout();
        tabCorpus.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }
    #endregion
    private System.Windows.Forms.Label lblSource = null!;
    private System.Windows.Forms.ComboBox cmbWorld = null!;
    private System.Windows.Forms.ComboBox cmbBand = null!;
    private System.Windows.Forms.ComboBox cmbRegister = null!;
    private System.Windows.Forms.Label lblContext = null!;
    private System.Windows.Forms.Button btnClear = null!;
    private System.Windows.Forms.Button btnCancel = null!;
    private System.Windows.Forms.TabControl tabsLab = null!;
    private System.Windows.Forms.TabPage tabDialogue = null!;
    private System.Windows.Forms.TabPage tabMentor = null!;
    private System.Windows.Forms.TabPage tabCorpus = null!;
    private System.Windows.Forms.TextBox txtTranscript = null!;
    private System.Windows.Forms.ListBox listTurns = null!;
    private System.Windows.Forms.TextBox txtTrace = null!;
    private System.Windows.Forms.TextBox txtInput = null!;
    private System.Windows.Forms.Button btnSend = null!;
    private System.Windows.Forms.CheckBox chkMentor = null!;
    private System.Windows.Forms.Label lblMentor = null!;
    private System.Windows.Forms.Label lblCorpus = null!;
    private System.Windows.Forms.Label lblStatus = null!;
    private System.Windows.Forms.Button btnMentorPreview = null!;
    private System.Windows.Forms.TextBox txtMentorPreview = null!;
    private System.Windows.Forms.CheckBox chkContextReviewed = null!;
    private System.Windows.Forms.Button btnAskMentor = null!;
    private System.Windows.Forms.TextBox txtAdvice = null!;
    private System.Windows.Forms.ComboBox cmbConfirmWorld = null!;
    private System.Windows.Forms.TextBox txtClarification = null!;
    private System.Windows.Forms.Button btnConfirm = null!;
    private System.Windows.Forms.Button btnDiscardMentor = null!;
    private System.Windows.Forms.Button btnUseMentorNote = null!;
    private System.Windows.Forms.TextBox txtNote = null!;
    private System.Windows.Forms.ComboBox cmbAct = null!;
    private System.Windows.Forms.ComboBox cmbTopic = null!;
    private System.Windows.Forms.ComboBox cmbGender = null!;
    private System.Windows.Forms.CheckBox chkScopeReviewed = null!;
    private System.Windows.Forms.Button btnSaveLesson = null!;
    private System.Windows.Forms.Button btnAddNote = null!;
    private System.Windows.Forms.Button btnSaveHistory = null!;
    private System.Windows.Forms.Button btnChooseCorpus = null!;
    private System.Windows.Forms.ListView listExcerpts = null!;
    private System.Windows.Forms.ColumnHeader columnExcerptId = null!;
    private System.Windows.Forms.ColumnHeader columnExcerptLanguage = null!;
    private System.Windows.Forms.ColumnHeader columnExcerptChannel = null!;
    private System.Windows.Forms.TextBox txtExcerpt = null!;
    private System.Windows.Forms.Label lblExcerptEdit = null!;
    private System.Windows.Forms.ComboBox cmbLanguageOverride = null!;
    private System.Windows.Forms.TextBox txtShareText = null!;
    private System.Windows.Forms.ComboBox cmbTransform = null!;
    private System.Windows.Forms.TextBox txtModelPreview = null!;
    private System.Windows.Forms.CheckBox chkPiiReviewed = null!;
    private System.Windows.Forms.CheckBox chkShareCorpus = null!;
    private System.Windows.Forms.Button btnTranslate = null!;
    private System.Windows.Forms.ListBox listSuggestions = null!;
    private System.Windows.Forms.TextBox txtCorpusAdvice = null!;
    private System.Windows.Forms.Button btnUseSuggestion = null!;
}
