#nullable enable
namespace PhantomSemanticStudio.WinForms;

partial class MainForm
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code
    private void InitializeComponent()
    {
            headerPanel = new System.Windows.Forms.Panel();
            lblTitle = new System.Windows.Forms.Label();
            lblHeader = new System.Windows.Forms.Label();
            btnCancel = new System.Windows.Forms.Button();
            tabs = new System.Windows.Forms.TabControl();
            tabGenerate = new System.Windows.Forms.TabPage();
            tabChat = new System.Windows.Forms.TabPage();
            tabLibrary = new System.Windows.Forms.TabPage();
            tabCandidates = new System.Windows.Forms.TabPage();
            tabExport = new System.Windows.Forms.TabPage();
            tabSettings = new System.Windows.Forms.TabPage();
            statusStrip = new System.Windows.Forms.StatusStrip();
            statusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            lblSnapshot = new System.Windows.Forms.Label();
            grpRequest = new System.Windows.Forms.GroupBox();
            lblAct = new System.Windows.Forms.Label();
            cmbAct = new System.Windows.Forms.ComboBox();
            lblTopic = new System.Windows.Forms.Label();
            cmbTopic = new System.Windows.Forms.ComboBox();
            lblBand = new System.Windows.Forms.Label();
            cmbBand = new System.Windows.Forms.ComboBox();
            lblGender = new System.Windows.Forms.Label();
            cmbGender = new System.Windows.Forms.ComboBox();
            lblRegister = new System.Windows.Forms.Label();
            cmbRegister = new System.Windows.Forms.ComboBox();
            lblInstruction = new System.Windows.Forms.Label();
            txtInstruction = new System.Windows.Forms.TextBox();
            lblWords = new System.Windows.Forms.Label();
            txtWords = new System.Windows.Forms.TextBox();
            grpGeneratorInfo = new System.Windows.Forms.GroupBox();
            txtGeneratorInfo = new System.Windows.Forms.TextBox();
            btnGenerate = new System.Windows.Forms.Button();
            btnToCandidates = new System.Windows.Forms.Button();
            lblBatch = new System.Windows.Forms.Label();
            nudCount = new System.Windows.Forms.NumericUpDown();
            lblChatWarning = new System.Windows.Forms.Label();
            txtConversation = new System.Windows.Forms.TextBox();
            txtChatInput = new System.Windows.Forms.TextBox();
            btnPreview = new System.Windows.Forms.Button();
            lblCorrection = new System.Windows.Forms.Label();
            txtCorrection = new System.Windows.Forms.TextBox();
            btnTeach = new System.Windows.Forms.Button();
            btnClearChat = new System.Windows.Forms.Button();
            grpLessons = new System.Windows.Forms.GroupBox();
            cmbLessons = new System.Windows.Forms.ComboBox();
            txtLessonDetails = new System.Windows.Forms.TextBox();
            btnApplyLesson = new System.Windows.Forms.Button();
            txtSearch = new System.Windows.Forms.TextBox();
            btnSearch = new System.Windows.Forms.Button();
            lblLibraryStats = new System.Windows.Forms.Label();
            gridLibrary = new System.Windows.Forms.DataGridView();
            gridLibraryColumn0 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridLibraryColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridLibraryColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridLibraryColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            txtLibraryDetails = new System.Windows.Forms.TextBox();
            lblCandidates = new System.Windows.Forms.Label();
            gridCandidates = new System.Windows.Forms.DataGridView();
            gridCandidatesColumn0 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridCandidatesColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridCandidatesColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridCandidatesColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            gridCandidatesColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblSelected = new System.Windows.Forms.Label();
            lblEdit = new System.Windows.Forms.Label();
            txtCandidateText = new System.Windows.Forms.TextBox();
            lblReviewNote = new System.Windows.Forms.Label();
            txtReviewNote = new System.Windows.Forms.TextBox();
            txtValidation = new System.Windows.Forms.TextBox();
            btnSaveCandidate = new System.Windows.Forms.Button();
            btnValidate = new System.Windows.Forms.Button();
            btnApprove = new System.Windows.Forms.Button();
            btnReject = new System.Windows.Forms.Button();
            txtExportInfo = new System.Windows.Forms.TextBox();
            btnCheckSource = new System.Windows.Forms.Button();
            btnExport = new System.Windows.Forms.Button();
            btnCopyWorkspace = new System.Windows.Forms.Button();
            txtExportLog = new System.Windows.Forms.TextBox();
            lblSourcePath = new System.Windows.Forms.Label();
            txtSourcePath = new System.Windows.Forms.TextBox();
            btnBrowseSource = new System.Windows.Forms.Button();
            lblEndpoint = new System.Windows.Forms.Label();
            txtEndpoint = new System.Windows.Forms.TextBox();
            lblModel = new System.Windows.Forms.Label();
            txtModel = new System.Windows.Forms.TextBox();
            lblToken = new System.Windows.Forms.Label();
            txtApiKey = new System.Windows.Forms.TextBox();
            lblTemp = new System.Windows.Forms.Label();
            nudTemperature = new System.Windows.Forms.NumericUpDown();
            lblTokens = new System.Windows.Forms.Label();
            nudTokens = new System.Windows.Forms.NumericUpDown();
            lblTimeout = new System.Windows.Forms.Label();
            nudTimeout = new System.Windows.Forms.NumericUpDown();
            lblWorkspace = new System.Windows.Forms.Label();
            txtWorkspace = new System.Windows.Forms.TextBox();
            btnSaveSettings = new System.Windows.Forms.Button();
            btnCheckLm = new System.Windows.Forms.Button();
            btnImport = new System.Windows.Forms.Button();
            txtSettingsResult = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)nudCount).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gridLibrary).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gridCandidates).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTemperature).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTokens).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTimeout).BeginInit();
            headerPanel.SuspendLayout();
            tabs.SuspendLayout();
            tabGenerate.SuspendLayout();
            tabChat.SuspendLayout();
            tabLibrary.SuspendLayout();
            tabCandidates.SuspendLayout();
            tabExport.SuspendLayout();
            tabSettings.SuspendLayout();
            statusStrip.SuspendLayout();
            grpRequest.SuspendLayout();
            grpGeneratorInfo.SuspendLayout();
            grpLessons.SuspendLayout();
            SuspendLayout();
            // headerPanel
            headerPanel.Name = "headerPanel";
            headerPanel.Location = new System.Drawing.Point(0, 0);
            headerPanel.Size = new System.Drawing.Size(1260, 76);
            headerPanel.Dock = System.Windows.Forms.DockStyle.Top;
            headerPanel.BackColor = System.Drawing.Color.FromArgb(31, 44, 61);
            // lblTitle
            lblTitle.Name = "lblTitle";
            lblTitle.Location = new System.Drawing.Point(20, 10);
            lblTitle.Size = new System.Drawing.Size(860, 32);
            lblTitle.Text = "Phantom Semantic Studio";
            lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            lblTitle.ForeColor = System.Drawing.Color.White;
            // lblHeader
            lblHeader.Name = "lblHeader";
            lblHeader.Location = new System.Drawing.Point(22, 45);
            lblHeader.Size = new System.Drawing.Size(1020, 22);
            lblHeader.Text = "HIGH FIVE • исходники только для чтения • публикация на сервер отсутствует";
            lblHeader.ForeColor = System.Drawing.Color.FromArgb(192, 221, 221);
            // btnCancel
            btnCancel.Name = "btnCancel";
            btnCancel.Location = new System.Drawing.Point(1090, 20);
            btnCancel.Size = new System.Drawing.Size(150, 36);
            btnCancel.Text = "Отменить операцию";
            btnCancel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnCancel.UseVisualStyleBackColor = true;
            btnCancel.Enabled = false;
            // tabs
            tabs.Name = "tabs";
            tabs.Location = new System.Drawing.Point(0, 76);
            tabs.Size = new System.Drawing.Size(1260, 734);
            tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            tabs.Padding = new System.Drawing.Point(14, 8);
            tabs.SelectedIndex = 0;
            // tabGenerate
            tabGenerate.Name = "tabGenerate";
            tabGenerate.Text = "Конструктор";
            tabGenerate.UseVisualStyleBackColor = true;
            tabGenerate.Padding = new System.Windows.Forms.Padding(12);
            // tabChat
            tabChat.Name = "tabChat";
            tabChat.Text = "Диалог и обучение";
            tabChat.UseVisualStyleBackColor = true;
            tabChat.Padding = new System.Windows.Forms.Padding(12);
            // tabLibrary
            tabLibrary.Name = "tabLibrary";
            tabLibrary.Text = "Библиотека";
            tabLibrary.UseVisualStyleBackColor = true;
            tabLibrary.Padding = new System.Windows.Forms.Padding(12);
            // tabCandidates
            tabCandidates.Name = "tabCandidates";
            tabCandidates.Text = "Кандидаты";
            tabCandidates.UseVisualStyleBackColor = true;
            tabCandidates.Padding = new System.Windows.Forms.Padding(12);
            // tabExport
            tabExport.Name = "tabExport";
            tabExport.Text = "Экспорт для ревью";
            tabExport.UseVisualStyleBackColor = true;
            tabExport.Padding = new System.Windows.Forms.Padding(12);
            // tabSettings
            tabSettings.Name = "tabSettings";
            tabSettings.Text = "Настройки";
            tabSettings.UseVisualStyleBackColor = true;
            tabSettings.Padding = new System.Windows.Forms.Padding(12);
            // statusStrip
            statusStrip.Name = "statusStrip";
            statusStrip.Dock = System.Windows.Forms.DockStyle.Bottom;
            statusLabel.Name = "statusLabel";
            statusLabel.Text = "Пак не импортирован. Начните с вкладки Настройки.";
            statusLabel.Spring = true;
            statusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // lblSnapshot
            lblSnapshot.Name = "lblSnapshot";
            lblSnapshot.Location = new System.Drawing.Point(16, 15);
            lblSnapshot.Size = new System.Drawing.Size(1210, 28);
            lblSnapshot.Text = "Пак ещё не импортирован. High Five остаётся только для чтения.";
            lblSnapshot.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // grpRequest
            grpRequest.Name = "grpRequest";
            grpRequest.Location = new System.Drawing.Point(16, 54);
            grpRequest.Size = new System.Drawing.Size(764, 538);
            grpRequest.Text = "Что добавить в разговоры";
            grpRequest.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // lblAct
            lblAct.Name = "lblAct";
            lblAct.Location = new System.Drawing.Point(18, 30);
            lblAct.Size = new System.Drawing.Size(714, 24);
            lblAct.Text = "Намерение (существующий act из пака)";
            // cmbAct
            cmbAct.Name = "cmbAct";
            cmbAct.Location = new System.Drawing.Point(18, 56);
            cmbAct.Size = new System.Drawing.Size(726, 29);
            cmbAct.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            cmbAct.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            // lblTopic
            lblTopic.Name = "lblTopic";
            lblTopic.Location = new System.Drawing.Point(18, 94);
            lblTopic.Size = new System.Drawing.Size(714, 24);
            lblTopic.Text = "Тема, связанная с выбранным намерением";
            // cmbTopic
            cmbTopic.Name = "cmbTopic";
            cmbTopic.Location = new System.Drawing.Point(18, 120);
            cmbTopic.Size = new System.Drawing.Size(726, 29);
            cmbTopic.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            cmbTopic.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            // lblBand
            lblBand.Name = "lblBand";
            lblBand.Location = new System.Drawing.Point(18, 160);
            lblBand.Size = new System.Drawing.Size(224, 24);
            lblBand.Text = "Отношения с собеседником";
            // cmbBand
            cmbBand.Name = "cmbBand";
            cmbBand.Location = new System.Drawing.Point(18, 186);
            cmbBand.Size = new System.Drawing.Size(224, 29);
            cmbBand.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            // lblGender
            lblGender.Name = "lblGender";
            lblGender.Location = new System.Drawing.Point(264, 160);
            lblGender.Size = new System.Drawing.Size(224, 24);
            lblGender.Text = "Пол говорящего фантома";
            // cmbGender
            cmbGender.Name = "cmbGender";
            cmbGender.Location = new System.Drawing.Point(264, 186);
            cmbGender.Size = new System.Drawing.Size(224, 29);
            cmbGender.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            // lblRegister
            lblRegister.Name = "lblRegister";
            lblRegister.Location = new System.Drawing.Point(510, 160);
            lblRegister.Size = new System.Drawing.Size(234, 24);
            lblRegister.Text = "Стиль речи";
            // cmbRegister
            cmbRegister.Name = "cmbRegister";
            cmbRegister.Location = new System.Drawing.Point(510, 186);
            cmbRegister.Size = new System.Drawing.Size(234, 29);
            cmbRegister.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            // lblInstruction
            lblInstruction.Name = "lblInstruction";
            lblInstruction.Location = new System.Drawing.Point(18, 226);
            lblInstruction.Size = new System.Drawing.Size(710, 24);
            lblInstruction.Text = "Характер, тема, нюансы и примеры желаемых ответов";
            // txtInstruction
            txtInstruction.Name = "txtInstruction";
            txtInstruction.Location = new System.Drawing.Point(18, 254);
            txtInstruction.Size = new System.Drawing.Size(726, 142);
            txtInstruction.Text = "Короткие живые ответы без канцелярита. Лёгкая доброжелательная ирония. Не выдумывай прошлые события и выполненные игровые действия.";
            txtInstruction.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtInstruction.MaxLength = 4000;
            txtInstruction.Multiline = true;
            txtInstruction.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtInstruction.ReadOnly = false;
            txtInstruction.MaxLength = 4000;
            // lblWords
            lblWords.Name = "lblWords";
            lblWords.Location = new System.Drawing.Point(18, 412);
            lblWords.Size = new System.Drawing.Size(710, 24);
            lblWords.Text = "Предпочтительные слова и обороты (не команды и не код)";
            lblWords.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // txtWords
            txtWords.Name = "txtWords";
            txtWords.Location = new System.Drawing.Point(18, 442);
            txtWords.Size = new System.Drawing.Size(726, 64);
            txtWords.Text = "";
            txtWords.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtWords.MaxLength = 4000;
            txtWords.Multiline = true;
            txtWords.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtWords.ReadOnly = false;
            txtWords.MaxLength = 600;
            // grpGeneratorInfo
            grpGeneratorInfo.Name = "grpGeneratorInfo";
            grpGeneratorInfo.Location = new System.Drawing.Point(798, 54);
            grpGeneratorInfo.Size = new System.Drawing.Size(428, 538);
            grpGeneratorInfo.Text = "Как это работает";
            grpGeneratorInfo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            // txtGeneratorInfo
            txtGeneratorInfo.Name = "txtGeneratorInfo";
            txtGeneratorInfo.Location = new System.Drawing.Point(16, 32);
            txtGeneratorInfo.Size = new System.Drawing.Size(396, 486);
            txtGeneratorInfo.Text = "1. Импортируйте свой High Five во вкладке «Настройки».\r\n\r\n2. Выберите существующее намерение и напишите пожелания.\r\n\r\n3. Gemma предложит только JSON-кандидаты входных фраз и ответов.\r\n\r\n4. Каждый кандидат остаётся черновиком до ручной проверки.\r\n\r\n5. Экспорт: REVIEW_ONLY / NOT_SERVER_VALIDATED. Только JSON, baseline и замечания.\r\n\r\nСмысловые повторы, грамматика, факты, условия и полнота profanity/mature проверки: не проверено.\r\n\r\nПол и темперамент — редакционные пожелания. Server filters не доказаны; XML в PSS-001 не экспортируется.";
            txtGeneratorInfo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtGeneratorInfo.MaxLength = 4000;
            txtGeneratorInfo.Multiline = true;
            txtGeneratorInfo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtGeneratorInfo.ReadOnly = true;
            txtGeneratorInfo.MaxLength = 20000;
            // btnGenerate
            btnGenerate.Name = "btnGenerate";
            btnGenerate.Location = new System.Drawing.Point(16, 614);
            btnGenerate.Size = new System.Drawing.Size(294, 40);
            btnGenerate.Text = "Сгенерировать кандидатов";
            btnGenerate.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnGenerate.UseVisualStyleBackColor = true;
            // btnToCandidates
            btnToCandidates.Name = "btnToCandidates";
            btnToCandidates.Location = new System.Drawing.Point(326, 614);
            btnToCandidates.Size = new System.Drawing.Size(224, 40);
            btnToCandidates.Text = "Перейти к кандидатам";
            btnToCandidates.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnToCandidates.UseVisualStyleBackColor = true;
            // lblBatch
            lblBatch.Name = "lblBatch";
            lblBatch.Location = new System.Drawing.Point(586, 625);
            lblBatch.Size = new System.Drawing.Size(170, 24);
            lblBatch.Text = "Размер партии (1–20):";
            lblBatch.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            // nudCount
            nudCount.Name = "nudCount";
            nudCount.Location = new System.Drawing.Point(774, 620);
            nudCount.Size = new System.Drawing.Size(84, 30);
            nudCount.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            nudCount.Minimum = 1;
            nudCount.Maximum = 20;
            nudCount.Value = 6;
            // lblChatWarning
            lblChatWarning.Name = "lblChatWarning";
            lblChatWarning.Location = new System.Drawing.Point(16, 14);
            lblChatWarning.Size = new System.Drawing.Size(1210, 45);
            lblChatWarning.Text = "Проверка по КАТАЛОГУ, не по Gemma и не по живому серверу. Без игровых действий, памяти и точного Java selector.";
            lblChatWarning.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // txtConversation
            txtConversation.Name = "txtConversation";
            txtConversation.Location = new System.Drawing.Point(16, 66);
            txtConversation.Size = new System.Drawing.Size(784, 320);
            txtConversation.Text = "";
            txtConversation.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            txtConversation.MaxLength = 4000;
            txtConversation.Multiline = true;
            txtConversation.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtConversation.ReadOnly = true;
            txtConversation.MaxLength = 200000;
            // txtChatInput
            txtChatInput.Name = "txtChatInput";
            txtChatInput.Location = new System.Drawing.Point(16, 402);
            txtChatInput.Size = new System.Drawing.Size(1028, 70);
            txtChatInput.Text = "";
            txtChatInput.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtChatInput.MaxLength = 4000;
            txtChatInput.Multiline = true;
            txtChatInput.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtChatInput.ReadOnly = false;
            txtChatInput.MaxLength = 256;
            // btnPreview
            btnPreview.Name = "btnPreview";
            btnPreview.Location = new System.Drawing.Point(1060, 402);
            btnPreview.Size = new System.Drawing.Size(166, 70);
            btnPreview.Text = "Ответ по паку";
            btnPreview.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnPreview.UseVisualStyleBackColor = true;
            // lblCorrection
            lblCorrection.Name = "lblCorrection";
            lblCorrection.Location = new System.Drawing.Point(16, 489);
            lblCorrection.Size = new System.Drawing.Size(1210, 24);
            lblCorrection.Text = "Объясни, что в ответе не так. Замечание само ничего в паке не меняет.";
            lblCorrection.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // txtCorrection
            txtCorrection.Name = "txtCorrection";
            txtCorrection.Location = new System.Drawing.Point(16, 517);
            txtCorrection.Size = new System.Drawing.Size(1210, 64);
            txtCorrection.Text = "";
            txtCorrection.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtCorrection.MaxLength = 4000;
            txtCorrection.Multiline = true;
            txtCorrection.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtCorrection.ReadOnly = false;
            txtCorrection.MaxLength = 3000;
            // btnTeach
            btnTeach.Name = "btnTeach";
            btnTeach.Location = new System.Drawing.Point(16, 601);
            btnTeach.Size = new System.Drawing.Size(304, 40);
            btnTeach.Text = "Сохранить замечание со scope";
            btnTeach.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnTeach.UseVisualStyleBackColor = true;
            // btnClearChat
            btnClearChat.Name = "btnClearChat";
            btnClearChat.Location = new System.Drawing.Point(336, 601);
            btnClearChat.Size = new System.Drawing.Size(204, 40);
            btnClearChat.Text = "Сбросить проверку";
            btnClearChat.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnClearChat.UseVisualStyleBackColor = true;
            // txtSearch
            txtSearch.Name = "txtSearch";
            txtSearch.Location = new System.Drawing.Point(16, 18);
            txtSearch.Size = new System.Drawing.Size(1018, 28);
            txtSearch.Text = "";
            txtSearch.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtSearch.MaxLength = 4000;
            // btnSearch
            btnSearch.Name = "btnSearch";
            btnSearch.Location = new System.Drawing.Point(1050, 16);
            btnSearch.Size = new System.Drawing.Size(176, 34);
            btnSearch.Text = "Найти";
            btnSearch.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnSearch.UseVisualStyleBackColor = true;
            // lblLibraryStats
            lblLibraryStats.Name = "lblLibraryStats";
            lblLibraryStats.Location = new System.Drawing.Point(16, 61);
            lblLibraryStats.Size = new System.Drawing.Size(1210, 24);
            lblLibraryStats.Text = "Показано 0 записей.";
            lblLibraryStats.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // gridLibrary
            gridLibrary.Name = "gridLibrary";
            gridLibrary.Location = new System.Drawing.Point(16, 96);
            gridLibrary.Size = new System.Drawing.Size(1210, 350);
            gridLibrary.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            gridLibrary.AllowUserToAddRows = false;
            gridLibrary.AllowUserToDeleteRows = false;
            gridLibrary.ReadOnly = true;
            gridLibrary.MultiSelect = false;
            gridLibrary.RowHeadersVisible = false;
            gridLibrary.AutoGenerateColumns = false;
            gridLibrary.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            gridLibrary.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            gridLibrary.BackgroundColor = System.Drawing.SystemColors.Window;
            gridLibrary.RowTemplate.Height = 28;
            gridLibraryColumn0.Name = "gridLibraryColumn0";
            gridLibraryColumn0.DataPropertyName = "Kind";
            gridLibraryColumn0.HeaderText = "Вид";
            gridLibraryColumn0.FillWeight = 55F;
            gridLibraryColumn0.ReadOnly = true;
            gridLibraryColumn1.Name = "gridLibraryColumn1";
            gridLibraryColumn1.DataPropertyName = "Id";
            gridLibraryColumn1.HeaderText = "ID";
            gridLibraryColumn1.FillWeight = 135F;
            gridLibraryColumn1.ReadOnly = true;
            gridLibraryColumn2.Name = "gridLibraryColumn2";
            gridLibraryColumn2.DataPropertyName = "Act";
            gridLibraryColumn2.HeaderText = "Намерение";
            gridLibraryColumn2.FillWeight = 120F;
            gridLibraryColumn2.ReadOnly = true;
            gridLibraryColumn3.Name = "gridLibraryColumn3";
            gridLibraryColumn3.DataPropertyName = "Text";
            gridLibraryColumn3.HeaderText = "Текст";
            gridLibraryColumn3.FillWeight = 250F;
            gridLibraryColumn3.ReadOnly = true;
            // txtLibraryDetails
            txtLibraryDetails.Name = "txtLibraryDetails";
            txtLibraryDetails.Location = new System.Drawing.Point(16, 463);
            txtLibraryDetails.Size = new System.Drawing.Size(1210, 178);
            txtLibraryDetails.Text = "Выберите запись для просмотра источника и условий.";
            txtLibraryDetails.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtLibraryDetails.MaxLength = 4000;
            txtLibraryDetails.Multiline = true;
            txtLibraryDetails.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtLibraryDetails.ReadOnly = true;
            txtLibraryDetails.MaxLength = 20000;
            // lblCandidates
            lblCandidates.Name = "lblCandidates";
            lblCandidates.Location = new System.Drawing.Point(16, 10);
            lblCandidates.Size = new System.Drawing.Size(1210, 24);
            lblCandidates.Text = "Нет автоодобрения. Исправление текста аннулирует прежнее одобрение.";
            lblCandidates.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // gridCandidates
            gridCandidates.Name = "gridCandidates";
            gridCandidates.Location = new System.Drawing.Point(16, 42);
            gridCandidates.Size = new System.Drawing.Size(1210, 270);
            gridCandidates.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            gridCandidates.AllowUserToAddRows = false;
            gridCandidates.AllowUserToDeleteRows = false;
            gridCandidates.ReadOnly = true;
            gridCandidates.MultiSelect = false;
            gridCandidates.RowHeadersVisible = false;
            gridCandidates.AutoGenerateColumns = false;
            gridCandidates.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            gridCandidates.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            gridCandidates.BackgroundColor = System.Drawing.SystemColors.Window;
            gridCandidates.RowTemplate.Height = 28;
            gridCandidatesColumn0.Name = "gridCandidatesColumn0";
            gridCandidatesColumn0.DataPropertyName = "State";
            gridCandidatesColumn0.HeaderText = "Статус";
            gridCandidatesColumn0.FillWeight = 80F;
            gridCandidatesColumn0.ReadOnly = true;
            gridCandidatesColumn1.Name = "gridCandidatesColumn1";
            gridCandidatesColumn1.DataPropertyName = "Kind";
            gridCandidatesColumn1.HeaderText = "Вид";
            gridCandidatesColumn1.FillWeight = 55F;
            gridCandidatesColumn1.ReadOnly = true;
            gridCandidatesColumn2.Name = "gridCandidatesColumn2";
            gridCandidatesColumn2.DataPropertyName = "Topic";
            gridCandidatesColumn2.HeaderText = "Тема";
            gridCandidatesColumn2.FillWeight = 110F;
            gridCandidatesColumn2.ReadOnly = true;
            gridCandidatesColumn3.Name = "gridCandidatesColumn3";
            gridCandidatesColumn3.DataPropertyName = "Gender";
            gridCandidatesColumn3.HeaderText = "Пол";
            gridCandidatesColumn3.FillWeight = 65F;
            gridCandidatesColumn3.ReadOnly = true;
            gridCandidatesColumn4.Name = "gridCandidatesColumn4";
            gridCandidatesColumn4.DataPropertyName = "Text";
            gridCandidatesColumn4.HeaderText = "Кандидат";
            gridCandidatesColumn4.FillWeight = 280F;
            gridCandidatesColumn4.ReadOnly = true;
            // lblSelected
            lblSelected.Name = "lblSelected";
            lblSelected.Location = new System.Drawing.Point(16, 328);
            lblSelected.Size = new System.Drawing.Size(1210, 38);
            lblSelected.Text = "Выберите кандидата.";
            lblSelected.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            // lblEdit
            lblEdit.Name = "lblEdit";
            lblEdit.Location = new System.Drawing.Point(16, 371);
            lblEdit.Size = new System.Drawing.Size(592, 24);
            lblEdit.Text = "Текст кандидата (после правки нажмите «Сохранить»)";
            lblEdit.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            // txtCandidateText
            txtCandidateText.Name = "txtCandidateText";
            txtCandidateText.Location = new System.Drawing.Point(16, 401);
            txtCandidateText.Size = new System.Drawing.Size(584, 70);
            txtCandidateText.Text = "";
            txtCandidateText.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            txtCandidateText.MaxLength = 4000;
            txtCandidateText.Multiline = true;
            txtCandidateText.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtCandidateText.ReadOnly = false;
            txtCandidateText.MaxLength = 512;
            // lblReviewNote
            lblReviewNote.Name = "lblReviewNote";
            lblReviewNote.Location = new System.Drawing.Point(16, 484);
            lblReviewNote.Size = new System.Drawing.Size(584, 24);
            lblReviewNote.Text = "Отметка ручной проверки / причина принятия";
            lblReviewNote.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            // txtReviewNote
            txtReviewNote.Name = "txtReviewNote";
            txtReviewNote.Location = new System.Drawing.Point(16, 513);
            txtReviewNote.Size = new System.Drawing.Size(584, 58);
            txtReviewNote.Text = "";
            txtReviewNote.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            txtReviewNote.MaxLength = 4000;
            txtReviewNote.Multiline = true;
            txtReviewNote.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtReviewNote.ReadOnly = false;
            txtReviewNote.MaxLength = 1000;
            // txtValidation
            txtValidation.Name = "txtValidation";
            txtValidation.Location = new System.Drawing.Point(618, 371);
            txtValidation.Size = new System.Drawing.Size(608, 255);
            txtValidation.Text = "Проверка ещё не запускалась. Автоматика не доказывает смысловую корректность.";
            txtValidation.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtValidation.MaxLength = 4000;
            txtValidation.Multiline = true;
            txtValidation.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtValidation.ReadOnly = true;
            txtValidation.MaxLength = 30000;
            // btnSaveCandidate
            btnSaveCandidate.Name = "btnSaveCandidate";
            btnSaveCandidate.Location = new System.Drawing.Point(16, 592);
            btnSaveCandidate.Size = new System.Drawing.Size(132, 38);
            btnSaveCandidate.Text = "Сохранить правку";
            btnSaveCandidate.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnSaveCandidate.UseVisualStyleBackColor = true;
            // btnValidate
            btnValidate.Name = "btnValidate";
            btnValidate.Location = new System.Drawing.Point(160, 592);
            btnValidate.Size = new System.Drawing.Size(132, 38);
            btnValidate.Text = "Проверить";
            btnValidate.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnValidate.UseVisualStyleBackColor = true;
            // btnApprove
            btnApprove.Name = "btnApprove";
            btnApprove.Location = new System.Drawing.Point(304, 592);
            btnApprove.Size = new System.Drawing.Size(140, 38);
            btnApprove.Text = "Одобрить";
            btnApprove.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnApprove.UseVisualStyleBackColor = true;
            // btnReject
            btnReject.Name = "btnReject";
            btnReject.Location = new System.Drawing.Point(456, 592);
            btnReject.Size = new System.Drawing.Size(144, 38);
            btnReject.Text = "Отклонить";
            btnReject.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnReject.UseVisualStyleBackColor = true;
            // txtExportInfo
            txtExportInfo.Name = "txtExportInfo";
            txtExportInfo.Location = new System.Drawing.Point(16, 18);
            txtExportInfo.Size = new System.Drawing.Size(1210, 182);
            txtExportInfo.Text = "REVIEW_ONLY / NOT_SERVER_VALIDATED\r\nJava-validator: NOT_RUN.\r\n\r\nZIP содержит одобренный JSON, исходный fingerprint и результаты предварительных проверок. XML не экспортируется: условия, profanity/mature и runtime-фильтры не доказаны.\r\n\r\nИсходные файлы L2J/v1/v2/v3/custom не заменяются. Установки и автопубликации нет.\r\n\r\nИзменение источника после импорта блокирует экспорт; изменения текста или отметки ревью отменяют approval. Пол и другие пожелания сохранены в JSON.";
            txtExportInfo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtExportInfo.MaxLength = 4000;
            txtExportInfo.Multiline = true;
            txtExportInfo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtExportInfo.ReadOnly = true;
            txtExportInfo.MaxLength = 20000;
            // btnCheckSource
            btnCheckSource.Name = "btnCheckSource";
            btnCheckSource.Location = new System.Drawing.Point(16, 218);
            btnCheckSource.Size = new System.Drawing.Size(258, 36);
            btnCheckSource.Text = "Проверить неизменность источника";
            btnCheckSource.UseVisualStyleBackColor = true;
            // btnExport
            btnExport.Name = "btnExport";
            btnExport.Location = new System.Drawing.Point(292, 218);
            btnExport.Size = new System.Drawing.Size(352, 36);
            btnExport.Text = "Экспорт одобренного для ревью";
            btnExport.UseVisualStyleBackColor = true;
            // btnCopyWorkspace
            btnCopyWorkspace.Name = "btnCopyWorkspace";
            btnCopyWorkspace.Location = new System.Drawing.Point(662, 218);
            btnCopyWorkspace.Size = new System.Drawing.Size(260, 36);
            btnCopyWorkspace.Text = "Скопировать путь workspace";
            btnCopyWorkspace.UseVisualStyleBackColor = true;
            // txtExportLog
            txtExportLog.Name = "txtExportLog";
            txtExportLog.Location = new System.Drawing.Point(16, 276);
            txtExportLog.Size = new System.Drawing.Size(1210, 365);
            txtExportLog.Text = "Экспорт ещё не выполнялся.";
            txtExportLog.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtExportLog.MaxLength = 4000;
            txtExportLog.Multiline = true;
            txtExportLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtExportLog.ReadOnly = true;
            txtExportLog.MaxLength = 100000;
            // lblSourcePath
            lblSourcePath.Name = "lblSourcePath";
            lblSourcePath.Location = new System.Drawing.Point(16, 20);
            lblSourcePath.Size = new System.Drawing.Size(1210, 24);
            lblSourcePath.Text = "Корень High Five (только чтение; не весь L2J)";
            // txtSourcePath
            txtSourcePath.Name = "txtSourcePath";
            txtSourcePath.Location = new System.Drawing.Point(16, 50);
            txtSourcePath.Size = new System.Drawing.Size(1052, 28);
            txtSourcePath.Text = "";
            txtSourcePath.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtSourcePath.MaxLength = 4000;
            // btnBrowseSource
            btnBrowseSource.Name = "btnBrowseSource";
            btnBrowseSource.Location = new System.Drawing.Point(1084, 47);
            btnBrowseSource.Size = new System.Drawing.Size(142, 34);
            btnBrowseSource.Text = "Выбрать…";
            btnBrowseSource.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnBrowseSource.UseVisualStyleBackColor = true;
            // lblEndpoint
            lblEndpoint.Name = "lblEndpoint";
            lblEndpoint.Location = new System.Drawing.Point(16, 100);
            lblEndpoint.Size = new System.Drawing.Size(1210, 24);
            lblEndpoint.Text = "LM Studio: локальный API-адрес";
            // txtEndpoint
            txtEndpoint.Name = "txtEndpoint";
            txtEndpoint.Location = new System.Drawing.Point(16, 130);
            txtEndpoint.Size = new System.Drawing.Size(1210, 28);
            txtEndpoint.Text = "";
            txtEndpoint.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtEndpoint.MaxLength = 4000;
            // lblModel
            lblModel.Name = "lblModel";
            lblModel.Location = new System.Drawing.Point(16, 178);
            lblModel.Size = new System.Drawing.Size(1210, 24);
            lblModel.Text = "Точный API identifier модели";
            // txtModel
            txtModel.Name = "txtModel";
            txtModel.Location = new System.Drawing.Point(16, 208);
            txtModel.Size = new System.Drawing.Size(1210, 28);
            txtModel.Text = "";
            txtModel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtModel.MaxLength = 4000;
            // lblToken
            lblToken.Name = "lblToken";
            lblToken.Location = new System.Drawing.Point(16, 256);
            lblToken.Size = new System.Drawing.Size(1210, 24);
            lblToken.Text = "API token, только если LM Studio требует авторизацию (не сохраняется)";
            // txtApiKey
            txtApiKey.Name = "txtApiKey";
            txtApiKey.Location = new System.Drawing.Point(16, 286);
            txtApiKey.Size = new System.Drawing.Size(1210, 28);
            txtApiKey.Text = "";
            txtApiKey.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtApiKey.MaxLength = 4000;
            txtApiKey.UseSystemPasswordChar = true;
            // lblTemp
            lblTemp.Name = "lblTemp";
            lblTemp.Location = new System.Drawing.Point(16, 336);
            lblTemp.Size = new System.Drawing.Size(210, 24);
            lblTemp.Text = "Температура";
            // nudTemperature
            nudTemperature.Name = "nudTemperature";
            nudTemperature.Location = new System.Drawing.Point(16, 364);
            nudTemperature.Size = new System.Drawing.Size(180, 30);
            nudTemperature.DecimalPlaces = 2;
            nudTemperature.Increment = new decimal(new int[] { 5, 0, 0, 131072 });
            nudTemperature.Maximum = 2;
            nudTemperature.Value = new decimal(new int[] { 70, 0, 0, 131072 });
            // lblTokens
            lblTokens.Name = "lblTokens";
            lblTokens.Location = new System.Drawing.Point(236, 336);
            lblTokens.Size = new System.Drawing.Size(210, 24);
            lblTokens.Text = "Максимум токенов";
            // nudTokens
            nudTokens.Name = "nudTokens";
            nudTokens.Location = new System.Drawing.Point(236, 364);
            nudTokens.Size = new System.Drawing.Size(180, 30);
            nudTokens.Minimum = 128;
            nudTokens.Maximum = 16384;
            nudTokens.Increment = 256;
            nudTokens.Value = 4096;
            // lblTimeout
            lblTimeout.Name = "lblTimeout";
            lblTimeout.Location = new System.Drawing.Point(456, 336);
            lblTimeout.Size = new System.Drawing.Size(240, 24);
            lblTimeout.Text = "Таймаут запроса, секунд";
            // nudTimeout
            nudTimeout.Name = "nudTimeout";
            nudTimeout.Location = new System.Drawing.Point(456, 364);
            nudTimeout.Size = new System.Drawing.Size(180, 30);
            nudTimeout.Minimum = 15;
            nudTimeout.Maximum = 600;
            nudTimeout.Increment = 15;
            nudTimeout.Value = 180;
            // lblWorkspace
            lblWorkspace.Name = "lblWorkspace";
            lblWorkspace.Location = new System.Drawing.Point(16, 417);
            lblWorkspace.Size = new System.Drawing.Size(1210, 24);
            lblWorkspace.Text = "Собственный workspace (не в папке L2J)";
            // txtWorkspace
            txtWorkspace.Name = "txtWorkspace";
            txtWorkspace.Location = new System.Drawing.Point(16, 447);
            txtWorkspace.Size = new System.Drawing.Size(1210, 28);
            txtWorkspace.Text = "";
            txtWorkspace.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtWorkspace.MaxLength = 4000;
            txtWorkspace.ReadOnly = true;
            // btnSaveSettings
            btnSaveSettings.Name = "btnSaveSettings";
            btnSaveSettings.Location = new System.Drawing.Point(16, 500);
            btnSaveSettings.Size = new System.Drawing.Size(214, 36);
            btnSaveSettings.Text = "Сохранить настройки";
            btnSaveSettings.UseVisualStyleBackColor = true;
            // btnCheckLm
            btnCheckLm.Name = "btnCheckLm";
            btnCheckLm.Location = new System.Drawing.Point(246, 500);
            btnCheckLm.Size = new System.Drawing.Size(266, 36);
            btnCheckLm.Text = "Проверить LM Studio / модель";
            btnCheckLm.UseVisualStyleBackColor = true;
            // btnImport
            btnImport.Name = "btnImport";
            btnImport.Location = new System.Drawing.Point(528, 500);
            btnImport.Size = new System.Drawing.Size(332, 36);
            btnImport.Text = "Импортировать пак (только чтение)";
            btnImport.UseVisualStyleBackColor = true;
            // txtSettingsResult
            txtSettingsResult.Name = "txtSettingsResult";
            txtSettingsResult.Location = new System.Drawing.Point(16, 558);
            txtSettingsResult.Size = new System.Drawing.Size(1210, 83);
            txtSettingsResult.Text = "Настройки загружаются при запуске, а не в конструкторе формы.";
            txtSettingsResult.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtSettingsResult.MaxLength = 4000;
            txtSettingsResult.Multiline = true;
            txtSettingsResult.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtSettingsResult.ReadOnly = true;
            txtSettingsResult.MaxLength = 10000;
            headerPanel.Controls.Add(lblTitle);
            headerPanel.Controls.Add(lblHeader);
            headerPanel.Controls.Add(btnCancel);
            tabs.Controls.Add(tabGenerate);
            tabs.Controls.Add(tabChat);
            tabs.Controls.Add(tabLibrary);
            tabs.Controls.Add(tabCandidates);
            tabs.Controls.Add(tabExport);
            tabs.Controls.Add(tabSettings);
            statusStrip.Items.Add(statusLabel);
            tabGenerate.Controls.Add(lblSnapshot);
            tabGenerate.Controls.Add(grpRequest);
            grpRequest.Controls.Add(lblAct);
            grpRequest.Controls.Add(cmbAct);
            grpRequest.Controls.Add(lblTopic);
            grpRequest.Controls.Add(cmbTopic);
            grpRequest.Controls.Add(lblBand);
            grpRequest.Controls.Add(cmbBand);
            grpRequest.Controls.Add(lblGender);
            grpRequest.Controls.Add(cmbGender);
            grpRequest.Controls.Add(lblRegister);
            grpRequest.Controls.Add(cmbRegister);
            grpRequest.Controls.Add(lblInstruction);
            grpRequest.Controls.Add(txtInstruction);
            grpRequest.Controls.Add(lblWords);
            grpRequest.Controls.Add(txtWords);
            tabGenerate.Controls.Add(grpGeneratorInfo);
            grpGeneratorInfo.Controls.Add(txtGeneratorInfo);
            tabGenerate.Controls.Add(btnGenerate);
            tabGenerate.Controls.Add(btnToCandidates);
            tabGenerate.Controls.Add(lblBatch);
            tabGenerate.Controls.Add(nudCount);
            grpLessons.Name = "grpLessons";
            grpLessons.Text = "Сохранённые замечания — явное применение";
            grpLessons.Location = new System.Drawing.Point(816, 66);
            grpLessons.Size = new System.Drawing.Size(410, 320);
            grpLessons.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            cmbLessons.Name = "cmbLessons";
            cmbLessons.Location = new System.Drawing.Point(12, 32);
            cmbLessons.Size = new System.Drawing.Size(386, 28);
            cmbLessons.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            cmbLessons.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            txtLessonDetails.Name = "txtLessonDetails";
            txtLessonDetails.Location = new System.Drawing.Point(12, 70);
            txtLessonDetails.Size = new System.Drawing.Size(386, 190);
            txtLessonDetails.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtLessonDetails.Multiline = true;
            txtLessonDetails.ReadOnly = true;
            txtLessonDetails.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            btnApplyLesson.Name = "btnApplyLesson";
            btnApplyLesson.Text = "Применить выбранное → конструктор";
            btnApplyLesson.Location = new System.Drawing.Point(12, 272);
            btnApplyLesson.Size = new System.Drawing.Size(386, 36);
            btnApplyLesson.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            btnApplyLesson.UseVisualStyleBackColor = true;
            grpLessons.Controls.Add(cmbLessons);
            grpLessons.Controls.Add(txtLessonDetails);
            grpLessons.Controls.Add(btnApplyLesson);
            tabChat.Controls.Add(grpLessons);
            tabChat.Controls.Add(lblChatWarning);
            tabChat.Controls.Add(txtConversation);
            tabChat.Controls.Add(txtChatInput);
            tabChat.Controls.Add(btnPreview);
            tabChat.Controls.Add(lblCorrection);
            tabChat.Controls.Add(txtCorrection);
            tabChat.Controls.Add(btnTeach);
            tabChat.Controls.Add(btnClearChat);
            tabLibrary.Controls.Add(txtSearch);
            tabLibrary.Controls.Add(btnSearch);
            tabLibrary.Controls.Add(lblLibraryStats);
            tabLibrary.Controls.Add(gridLibrary);
            gridLibrary.Columns.Add(gridLibraryColumn0);
            gridLibrary.Columns.Add(gridLibraryColumn1);
            gridLibrary.Columns.Add(gridLibraryColumn2);
            gridLibrary.Columns.Add(gridLibraryColumn3);
            tabLibrary.Controls.Add(txtLibraryDetails);
            tabCandidates.Controls.Add(lblCandidates);
            tabCandidates.Controls.Add(gridCandidates);
            gridCandidates.Columns.Add(gridCandidatesColumn0);
            gridCandidates.Columns.Add(gridCandidatesColumn1);
            gridCandidates.Columns.Add(gridCandidatesColumn2);
            gridCandidates.Columns.Add(gridCandidatesColumn3);
            gridCandidates.Columns.Add(gridCandidatesColumn4);
            tabCandidates.Controls.Add(lblSelected);
            tabCandidates.Controls.Add(lblEdit);
            tabCandidates.Controls.Add(txtCandidateText);
            tabCandidates.Controls.Add(lblReviewNote);
            tabCandidates.Controls.Add(txtReviewNote);
            tabCandidates.Controls.Add(txtValidation);
            tabCandidates.Controls.Add(btnSaveCandidate);
            tabCandidates.Controls.Add(btnValidate);
            tabCandidates.Controls.Add(btnApprove);
            tabCandidates.Controls.Add(btnReject);
            tabExport.Controls.Add(txtExportInfo);
            tabExport.Controls.Add(btnCheckSource);
            tabExport.Controls.Add(btnExport);
            tabExport.Controls.Add(btnCopyWorkspace);
            tabExport.Controls.Add(txtExportLog);
            tabSettings.Controls.Add(lblSourcePath);
            tabSettings.Controls.Add(txtSourcePath);
            tabSettings.Controls.Add(btnBrowseSource);
            tabSettings.Controls.Add(lblEndpoint);
            tabSettings.Controls.Add(txtEndpoint);
            tabSettings.Controls.Add(lblModel);
            tabSettings.Controls.Add(txtModel);
            tabSettings.Controls.Add(lblToken);
            tabSettings.Controls.Add(txtApiKey);
            tabSettings.Controls.Add(lblTemp);
            tabSettings.Controls.Add(nudTemperature);
            tabSettings.Controls.Add(lblTokens);
            tabSettings.Controls.Add(nudTokens);
            tabSettings.Controls.Add(lblTimeout);
            tabSettings.Controls.Add(nudTimeout);
            tabSettings.Controls.Add(lblWorkspace);
            tabSettings.Controls.Add(txtWorkspace);
            tabSettings.Controls.Add(btnSaveSettings);
            tabSettings.Controls.Add(btnCheckLm);
            tabSettings.Controls.Add(btnImport);
            tabSettings.Controls.Add(txtSettingsResult);
            btnCancel.Click += Cancel_Click;
            cmbAct.SelectedIndexChanged += Act_Changed;
            btnGenerate.Click += Generate_Click;
            btnToCandidates.Click += ToCandidates_Click;
            btnPreview.Click += Preview_Click;
            btnTeach.Click += Teach_Click;
            cmbLessons.SelectedIndexChanged += LessonSelection_Changed;
            btnApplyLesson.Click += ApplyLesson_Click;
            tabs.Selecting += Tabs_Selecting;
            btnClearChat.Click += ClearChat_Click;
            btnSearch.Click += Search_Click;
            gridLibrary.SelectionChanged += LibrarySelection_Changed;
            gridCandidates.CurrentCellChanged += CandidateSelection_Changed;
            btnSaveCandidate.Click += SaveCandidate_Click;
            btnValidate.Click += Validate_Click;
            btnApprove.Click += Approve_Click;
            btnReject.Click += Reject_Click;
            btnCheckSource.Click += CheckSource_Click;
            btnExport.Click += Export_Click;
            btnCopyWorkspace.Click += CopyWorkspace_Click;
            btnBrowseSource.Click += BrowseSource_Click;
            btnSaveSettings.Click += SaveSettings_Click;
            btnCheckLm.Click += CheckLm_Click;
            btnImport.Click += Import_Click;
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Font = new System.Drawing.Font("Segoe UI", 10F);
            ClientSize = new System.Drawing.Size(1260, 850);
            MinimumSize = new System.Drawing.Size(1276, 810);
            StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            Text = "Phantom Semantic Studio — 0.1 / только чтение L2J";
            Name = "MainForm";
            Controls.Add(tabs);
            Controls.Add(headerPanel);
            Controls.Add(statusStrip);
            Shown += MainForm_Shown;
            FormClosing += MainForm_FormClosing;
            FormClosed += MainForm_FormClosed;
            ((System.ComponentModel.ISupportInitialize)nudCount).EndInit();
            ((System.ComponentModel.ISupportInitialize)gridLibrary).EndInit();
            ((System.ComponentModel.ISupportInitialize)gridCandidates).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTemperature).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTokens).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTimeout).EndInit();
            headerPanel.ResumeLayout(false);
            headerPanel.PerformLayout();
            tabs.ResumeLayout(false);
            tabs.PerformLayout();
            tabGenerate.ResumeLayout(false);
            tabGenerate.PerformLayout();
            tabChat.ResumeLayout(false);
            tabChat.PerformLayout();
            tabLibrary.ResumeLayout(false);
            tabLibrary.PerformLayout();
            tabCandidates.ResumeLayout(false);
            tabCandidates.PerformLayout();
            tabExport.ResumeLayout(false);
            tabExport.PerformLayout();
            tabSettings.ResumeLayout(false);
            tabSettings.PerformLayout();
            statusStrip.ResumeLayout(false);
            statusStrip.PerformLayout();
            grpRequest.ResumeLayout(false);
            grpRequest.PerformLayout();
            grpGeneratorInfo.ResumeLayout(false);
            grpGeneratorInfo.PerformLayout();
            grpLessons.ResumeLayout(false);
            grpLessons.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
    }
    #endregion

    private System.Windows.Forms.Panel headerPanel = null!;
    private System.Windows.Forms.Label lblTitle = null!;
    private System.Windows.Forms.Label lblHeader = null!;
    private System.Windows.Forms.Button btnCancel = null!;
    private System.Windows.Forms.TabControl tabs = null!;
    private System.Windows.Forms.TabPage tabGenerate = null!;
    private System.Windows.Forms.TabPage tabChat = null!;
    private System.Windows.Forms.TabPage tabLibrary = null!;
    private System.Windows.Forms.TabPage tabCandidates = null!;
    private System.Windows.Forms.TabPage tabExport = null!;
    private System.Windows.Forms.TabPage tabSettings = null!;
    private System.Windows.Forms.StatusStrip statusStrip = null!;
    private System.Windows.Forms.ToolStripStatusLabel statusLabel = null!;
    private System.Windows.Forms.Label lblSnapshot = null!;
    private System.Windows.Forms.GroupBox grpRequest = null!;
    private System.Windows.Forms.Label lblAct = null!;
    private System.Windows.Forms.ComboBox cmbAct = null!;
    private System.Windows.Forms.Label lblTopic = null!;
    private System.Windows.Forms.ComboBox cmbTopic = null!;
    private System.Windows.Forms.Label lblBand = null!;
    private System.Windows.Forms.ComboBox cmbBand = null!;
    private System.Windows.Forms.Label lblGender = null!;
    private System.Windows.Forms.ComboBox cmbGender = null!;
    private System.Windows.Forms.Label lblRegister = null!;
    private System.Windows.Forms.ComboBox cmbRegister = null!;
    private System.Windows.Forms.Label lblInstruction = null!;
    private System.Windows.Forms.TextBox txtInstruction = null!;
    private System.Windows.Forms.Label lblWords = null!;
    private System.Windows.Forms.TextBox txtWords = null!;
    private System.Windows.Forms.GroupBox grpGeneratorInfo = null!;
    private System.Windows.Forms.TextBox txtGeneratorInfo = null!;
    private System.Windows.Forms.Button btnGenerate = null!;
    private System.Windows.Forms.Button btnToCandidates = null!;
    private System.Windows.Forms.Label lblBatch = null!;
    private System.Windows.Forms.NumericUpDown nudCount = null!;
    private System.Windows.Forms.Label lblChatWarning = null!;
    private System.Windows.Forms.TextBox txtConversation = null!;
    private System.Windows.Forms.TextBox txtChatInput = null!;
    private System.Windows.Forms.Button btnPreview = null!;
    private System.Windows.Forms.Label lblCorrection = null!;
    private System.Windows.Forms.TextBox txtCorrection = null!;
    private System.Windows.Forms.Button btnTeach = null!;
    private System.Windows.Forms.GroupBox grpLessons = null!;
    private System.Windows.Forms.ComboBox cmbLessons = null!;
    private System.Windows.Forms.TextBox txtLessonDetails = null!;
    private System.Windows.Forms.Button btnApplyLesson = null!;
    private System.Windows.Forms.Button btnClearChat = null!;
    private System.Windows.Forms.TextBox txtSearch = null!;
    private System.Windows.Forms.Button btnSearch = null!;
    private System.Windows.Forms.Label lblLibraryStats = null!;
    private System.Windows.Forms.DataGridView gridLibrary = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridLibraryColumn0 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridLibraryColumn1 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridLibraryColumn2 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridLibraryColumn3 = null!;
    private System.Windows.Forms.TextBox txtLibraryDetails = null!;
    private System.Windows.Forms.Label lblCandidates = null!;
    private System.Windows.Forms.DataGridView gridCandidates = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridCandidatesColumn0 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridCandidatesColumn1 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridCandidatesColumn2 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridCandidatesColumn3 = null!;
    private System.Windows.Forms.DataGridViewTextBoxColumn gridCandidatesColumn4 = null!;
    private System.Windows.Forms.Label lblSelected = null!;
    private System.Windows.Forms.Label lblEdit = null!;
    private System.Windows.Forms.TextBox txtCandidateText = null!;
    private System.Windows.Forms.Label lblReviewNote = null!;
    private System.Windows.Forms.TextBox txtReviewNote = null!;
    private System.Windows.Forms.TextBox txtValidation = null!;
    private System.Windows.Forms.Button btnSaveCandidate = null!;
    private System.Windows.Forms.Button btnValidate = null!;
    private System.Windows.Forms.Button btnApprove = null!;
    private System.Windows.Forms.Button btnReject = null!;
    private System.Windows.Forms.TextBox txtExportInfo = null!;
    private System.Windows.Forms.Button btnCheckSource = null!;
    private System.Windows.Forms.Button btnExport = null!;
    private System.Windows.Forms.Button btnCopyWorkspace = null!;
    private System.Windows.Forms.TextBox txtExportLog = null!;
    private System.Windows.Forms.Label lblSourcePath = null!;
    private System.Windows.Forms.TextBox txtSourcePath = null!;
    private System.Windows.Forms.Button btnBrowseSource = null!;
    private System.Windows.Forms.Label lblEndpoint = null!;
    private System.Windows.Forms.TextBox txtEndpoint = null!;
    private System.Windows.Forms.Label lblModel = null!;
    private System.Windows.Forms.TextBox txtModel = null!;
    private System.Windows.Forms.Label lblToken = null!;
    private System.Windows.Forms.TextBox txtApiKey = null!;
    private System.Windows.Forms.Label lblTemp = null!;
    private System.Windows.Forms.NumericUpDown nudTemperature = null!;
    private System.Windows.Forms.Label lblTokens = null!;
    private System.Windows.Forms.NumericUpDown nudTokens = null!;
    private System.Windows.Forms.Label lblTimeout = null!;
    private System.Windows.Forms.NumericUpDown nudTimeout = null!;
    private System.Windows.Forms.Label lblWorkspace = null!;
    private System.Windows.Forms.TextBox txtWorkspace = null!;
    private System.Windows.Forms.Button btnSaveSettings = null!;
    private System.Windows.Forms.Button btnCheckLm = null!;
    private System.Windows.Forms.Button btnImport = null!;
    private System.Windows.Forms.TextBox txtSettingsResult = null!;
}
